### ISSUE TITLE
Modest PEP-8 adherence?

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#82] opened 2020-03-02 23:36 UTC
I've somewhat standardized my python projects with a loose adherence to PEP-8 standards. My typical `setup.cfg`:

```
[pycodestyle]
ignore = E303,W391
max-line-length = 90
```

Thoughts? If acceptable I'll start light reformatting as I touch different areas.

**Comment by stepansnigirev** [comment] 2020-03-02 23:48
Sounds good.

**Comment by k9ert** [comment] 2020-03-10 12:33
I like it! Gradually, we should also enforce it by the CI. The trick i usually to gradually subordinate bigger chunks of the codebase to the new policies.
I don't think it makes sense to change the style if it's not checked afterwards. Therefore imho this should first be solved in the CI. A simple solution e.g. could be to append such lines in the .travis.yml: 
pycodestyle --first src/cryptoadvance/specter/somefile.py

and fix somefile.py in the same commit.
If you start with it, i'll do another file :-).

**Comment by k9ert** [comment] 2020-09-11 12:30
might be a duplicate of #286 . Or maybe only related.

**Comment by stepansnigirev** [comment] 2020-09-30 20:11
Everything is blacklified now

**Closed by stepansnigirev** 2020-09-30 20:11 UTC
Labels: chore
