### ISSUE TITLE
Can not launch Specter after v1.3.0

### ISSUE THREAD

**Issue by Yochigamma** [cryptoadvance/specter-desktop#1377] opened 2021-08-31 21:39 UTC
I have downloaded and installed every Specter Desktop version to my PC since v1.3.0. (latest attempt has been v1.6.0)

Each time, the launching specter desktop pacman screen comes up and the animation plays for hours. Eventually I just close the program, usually after waiting overnight. 

To my surprise, when I launched v1.3.0 today it launched successfully. I will continue using this version until I can launch any updates. 

I'm running Windows 10. Any advice is appreciated! 

Josh

**Comment by k9ert** [comment] 2021-09-01 15:26
We should probably make a troubleshooting guide exactly to this issue. The most likely reason for this is that another instance of specter is alredy running. Here is a short guide on how to troubleshoot:

# check the logs
The logs are usually in the `.specter` subfolder of your homediretory. There, you might find a file called `specter.log` which might contain content which gives a hint on what's wrong.

# check port 25441
Maybe there is another instance running, still. So check that via opening your brower here: [http://localhost:25441](http://localhost:25441)
If that's the case, the most easy solution is to reboot your computer.

# check whether the binary is existing
The first thing specter is doing if you start up the app is downloading the correct specterd from the github-release-page and storing that executable in the `Homefolder/.specter/specterd-binaries` subfolder. You should find a file called `specterd`.
If the file is there but you still get Pacman, try to start the specterd manually via the commandline.

# specterd is not in place
So if that file is not there, then open a commandline and execute the AppImage (or the Windows-Executable) manually and look at the output it generates.

Hope that give some ideas on how to troubleshoot. This guide might be a bit rough around the corners. Please give me feedback where you need more help and maybe we can improve it and put it into the docs directory eventually.

**Comment by p-bateman** [comment] 2021-09-14 21:10
I'm having the same problem. I had to change the network on my node (router died) and wanted to change that in specter but I'm stuck in the pacman screen.

Error Log:
[2021-09-14 22:53:58,895] ERROR in wallet_manager: Prevented Trying to update wallet_Manager with broken <BitcoinRpc http://XXXX:8332>
[2021-09-14 22:53:58,896] INFO in wallet_manager: Specter seems to be disconnected from Bitcoin Core. Skipping wallets update.
[2021-09-14 22:53:58,897] INFO in checker: Checker executed within 168.396 seconds. This message won't show again until stopped and started.
2021-09-14 23:07:50,979] ERROR in node: HTTPConnectionPool(host='XXXX', port=8332): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F50D175970>: Failed to establish a new connection: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat'))

The XXXX is the old node address. But I can't change it because Specter is stuck in pacman mode ;) 

Sorry I'm not suuuuper tech savy. Not sure what to do....

**Comment by k9ert** [comment] 2021-09-28 09:27
This will also significantly improve in v1.6.1 where you'll be able to check the logs and the error-messages will be much better if something goes wrong. You can already test the upcoming version here:
https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.6.1-pre15

**Comment by k9ert** [comment] 2021-11-30 15:12
Closing this for now.

**Closed by k9ert** 2021-11-30 15:12 UTC
Labels: bug
