### ISSUE TITLE
Fresh install v1.8.1 on win11 fails with specterd exited with code 1

### ISSUE THREAD

**Issue by marcelrv** [cryptoadvance/specter-desktop#1553] opened 2022-02-03 18:42 UTC
Trying to run / fresh install specter-desktop on win11 system.
Unfortunately fails with a `specterd exited with code 1`

Logerror does not directly indicates a way around the issue

```
2022-02-03T18:35:01.179Z [info] : Framework Ready! Starting tray Icon ...
2022-02-03T18:35:01.201Z [info] : Framework Ready! Initializing Main-Window, populating Menu ...
2022-02-03T18:35:01.277Z [info] : Creating specterd-binaries folder
2022-02-03T18:35:01.277Z [info] : Updating C:\Users\UserId\.specter\app_settings.json : {"mode":"specterd","specterURL":"http://localhost:25441","tor":false,"proxyURL":"socks5://127.0.0.1:9050","specterdVersion":"v1.8.1","specterdHash":"466d34f9c4fc78b774815733333afce8240862a57e053f0826aee3700af219a4b","specterdCLIArgs":"","versionInitialized":false}
2022-02-03T18:35:01.280Z [info] : Using version 
2022-02-03T18:35:01.280Z [info] : https://github.com/cryptoadvance/specter-desktop/releases/download/v1.8.1/specterd-v1.8.1-win64.zip
2022-02-03T18:35:01.839Z [info] : content-type:
2022-02-03T18:35:01.839Z [info] : content-length:
2022-02-03T18:35:05.940Z [info] : Starting specterd C:\Users\UserId\.specter\specterd-binaries/specterd.exe server,--no-filelog
2022-02-03T18:35:14.719Z [info] : stderr-SPECTERD: INFO in server: Configuration: cryptoadvance.specter.config.ProductionConfig

2022-02-03T18:35:14.723Z [info] : stderr-SPECTERD: INFO in specter_migrator: Initiated MigDataManager(C:\Users\UserId/.specter\migration_data.json events:0 execs:0 )
SPECTERD: INFO in specter_migrator: A new version has been started compared to last time: v1.8.1

2022-02-03T18:35:14.728Z [info] : stderr-Traceback (most recent call last):
  File "specterd.py", line 4, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "cryptoadvance\specter\cli\cli_server.py", line 114, in server
  File "cryptoadvance\specter\server.py", line 104, in init_app
  File "cryptoadvance\specter\util\specter_migrator.py", line 125, in execute_migrations
  File "cryptoadvance\specter\util\specter_migrator.py", line 107, in plan_migration
  File "cryptoadvance\specter\util\specter_migrator.py", line 161, in get_migration_classes
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgutil.py", line 71, in _pyi_pkgutil_iter_modules
AssertionError
[22640] Failed to execute script 'specterd' due to unhandled exception!

2022-02-03T18:35:14.728Z [info] : stdout-Initializing HWI...

2022-02-03T18:35:15.095Z [error] : specterd exited with code 1
2022-02-03T18:35:15.096Z [info] : child process exited with code 1
```

![image](https://user-images.githubusercontent.com/5871213/152407351-7d73d695-3111-4ba1-b568-418e7ecf0b43.png)

**Comment by marcelrv** [comment] 2022-02-03 19:11
Note when running specterd with debug flag this is the output

```
Microsoft Windows [Version 10.0.22000.434]
(c) Microsoft Corporation. All rights reserved.

C:\Users\UserId\.specter\specterd-binaries>specterd.exe --debug server
Initializing HWI...
[   INFO] in          server: Configuration: cryptoadvance.specter.config.ProductionConfig
[  DEBUG] in genericdata_manager: Loading existing file C:\Users\UserId/.specter\migration_data.json
[   INFO] in specter_migrator: Initiated MigDataManager(C:\Users\UserId/.specter\migration_data.json events:1 execs:0 )
[  DEBUG] in specter_migrator: Initiated SpecterMigrator(MigDataManager(C:\Users\UserId/.specter\migration_data.json events:1 execs:0 ))
Traceback (most recent call last):
  File "specterd.py", line 4, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "cryptoadvance\specter\cli\cli_server.py", line 114, in server
  File "cryptoadvance\specter\server.py", line 104, in init_app
  File "cryptoadvance\specter\util\specter_migrator.py", line 125, in execute_migrations
  File "cryptoadvance\specter\util\specter_migrator.py", line 107, in plan_migration
  File "cryptoadvance\specter\util\specter_migrator.py", line 161, in get_migration_classes
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgutil.py", line 71, in _pyi_pkgutil_iter_modules
AssertionError
[17904] Failed to execute script 'specterd' due to unhandled exception!

C:\Users\UserId\.specter\specterd-binaries>
```

**Comment by LucasStergianis** [comment] 2022-02-03 20:32
I have the same exact issue. I just Factory Reset my computer, clean install of windows, clean install of specter.v1.8.1 on windows 10 and it failed with the same error.
 " Specter Desktop encounter an error: specterd exited with code 1. Check the logs in the menu!" 
I did everything properly and came here to see if this issue has been posted yet, which it has. That being said i have not figured out how to fix this Bug. If i do i will let you know.

**Comment by LucasStergianis** [comment] 2022-02-03 20:34
Its 100% not my computer because everything has been installed  "Clean" and you have the same exact problem as I do. Any developers on here know what's going on with the new release ?  If i knew how to code i would help but i am still a noobie.

**Comment by LucasStergianis** [comment] 2022-02-04 00:02
The only current work-around is installing v1.7.2 and using that until the newer releases get fixed for windows. 
[v1.8.0 & v1.8.1] do not install properly at the moment. I tried all three of them on a clean install of windows 10.

**Comment by k9ert** [comment] 2022-02-04 09:17
Thanks for the report. I have an idea what the reason for this is. It's a variation of https://github.com/pyinstaller/pyinstaller/issues/6537 but i'm still confused why this is an issue under win as we fixed it by #1533 and monkey-patching the hook, but only for MacOS.

So maybe we need to do that for specific versions of windows as well. The problem is described in the issue at the pyinstaller. Maybe Windows is also using two different folders where stuff is unpacked or it uses symlinks like MacOS.

In that case, my solution was:
* Adding two lines to the [script](https://github.com/cryptoadvance/specter-desktop/blob/master/pyinstaller/rthooks/pyi_rth_pkgutil.py#L63-L64) which checks whether the symlink is the issue
* [copy the hook](https://github.com/cryptoadvance/specter-desktop/blob/master/pyinstaller/build-osx.sh#L110-L111) before the build starts to the folder from where pyinstaller is loading the runtime-hooks.

Help would be much appreciated.

**Comment by k9ert** [comment] 2022-02-04 09:41
Interesting enough exactly one day before i filed my issue, someone on there side started to implement a proper fix on https://github.com/pyinstaller/pyinstaller/issues/6528 .
This is already released on version 4.9 of the pyinstaller. so hopefully this will also fix this issue.
Working on it ...

**Comment by k9ert** [comment] 2022-02-04 11:18
I just try to reproduce on my Windows10 but it's not an issue there. We'll upgrade the pyinstaller anyway and i hope this is fixed witht the next version (which will come the within the next week probably). 
Do you have a ramdisk or some fancy filesystem-layout or anthing like that?

**Closed** 2022-02-04 12:09 UTC
Labels: bug

**Comment by marcelrv** [comment] 2022-02-04 14:12
I installed the 1.8.2-pre and was able to finish the install.
` Do you have a ramdisk or some fancy filesystem-layout or anthing like that?
`
No, just windows 11, and running the installer. 
Note, I did see that specter installed stuff all over the place,
e.g. I found folder in in the [user]/.specter , in [user]/appdata/roaming, in [user]appdata/low

**Comment by k9ert** [comment] 2022-02-06 20:45
> e.g. I found folder in in the [user]/.specter , in [user]/appdata/roaming, in [user]appdata/low

I'm aware of `.specter` but not the other stuff. Might be from the exe-installer.
