### ISSUE TITLE
PDF backup displays wrong address type (nested segwit instead of native segwit)

### ISSUE THREAD

**Issue by s-tikhomirov** [cryptoadvance/specter-desktop#880] opened 2021-01-17 12:52 UTC
I have a multi-sig wallet with bech32 addresses. However, the PDF backup says "multisig (sorted, nested segwit)". Isn't there a contradiction? The PDF wallet also displays master public keys as "xpub...", but if I open the wallet and choose Settings - Show keys details, it shows the keys starting with "Zpub...".

**Comment by mmikeww** [comment] 2021-01-17 15:37
I mentioned this in #876 and there will be an option to export Zpubs to PDF in the next version.

I don't know about the "nested segwit" however

Also @ben-kaufman , similar issue with `Wallet -> Settings -> Export -> Export button -> Save JSON file` the json file is saved with xpubs instead of Zpubs

**Comment by ben-kaufman** [comment] 2021-01-18 07:03
@s-tikhomirov Hi, we had an issue with the PDF saying nested segwit regardless of the actual address type which was fixed in v1.0.0, I assume you have tried with an older version? If so can you please try with that one?
Regarding xpub/ zpub, a PR for the next version was already merged to allow toggling between the xpub and zpub formats, making the xpub default everywhere for consistency, it'll be out in the next release.

@mmikeww This part is intentionally with xpubs only since it's in a specific export format for compatibility with other software using that same standard. It uses descriptors, which is a newer standard making SLIP132 (zpubs etc.) obsolete, so that part is just the xpubs. It is always possible to derive the zpubs from them, but these are anyway only useful for Electrum, which has its own export format you can export in the button at the bottom of that export popup.

**Comment by mmikeww** [comment] 2021-01-18 14:32
> we had an issue with the PDF saying nested segwit regardless of the actual address type which was fixed in v1.0.0

Confirmed fixed in 1.0 for me

> This part is intentionally with xpubs only since it's in a specific export format for compatibility with other software using that same standard

Ok!

**Comment by s-tikhomirov** [comment] 2021-01-18 22:11
> I assume you have tried with an older version? If so can you please try with that one?

Checked with 1.0: PDF export correctly displays "native segwit" now, thanks!

**Closed** 2021-01-19 07:05 UTC
