### ISSUE TITLE
BS Jade not being detected over HWI Bridge

### ISSUE THREAD

**Issue by ekmerrick** [cryptoadvance/specter-desktop#1251] opened 2021-06-23 19:01 UTC
I can connect other hardware wallets to Specter Desktop V1.4.5 over HWI bridge but not a BS Jade hardware wallet. Specter Desktop is stuck saying it is detecting devices and asks for the device to be plugged in. I'm running the bridge from a remote Specter Desktop Server on Umbrel to Spector Desktop on PC.

**Comment by ben-kaufman** [comment] 2021-06-23 19:06
Hi, did you update the local Specter version as well or only the Umbrel version? You have to update both to 1.4.5 for it to work.

**Comment by ekmerrick** [comment] 2021-06-23 19:10
Oh, I didn't do that. I'll try it and get back to you.

**Comment by ekmerrick** [comment] 2021-06-23 19:39
So I have my jade on the latest firmware, the specter desktop client on my PC on the latest firmware v1.4.5, and the specter desktop server on umbrel on the latest firmware v1.4.5, and it's still not able to detect the Blockstream Jade. I attempted to connect the device in two ways. The first through the HWI bridge to my umbrel node and the second way by running specter desktop client in local mode, and neither will work.

**Comment by k9ert** [comment] 2021-07-19 09:35
I just tried that and couldn't reproduce the the issue. Can you please try again witht he newest `1-5-0`. Hope that fixes the issue.

**Comment by ekmerrick** [comment] 2021-07-24 13:42
I think it's an issue with the Jade and not Specter.  I will try again when I get Specter updated on my umbrel.

**Comment by k9ert** [comment] 2021-07-26 08:20
IMHO you should test it on a local test-instance. If it's on your umbrel, you might have all sorts of other issues and having a local (test-) installation is as easy as downloading a file.

**Comment by k9ert** [comment] 2021-08-31 12:12
Any update on this?

**Comment by k9ert** [comment] 2021-09-02 10:07
I just tested extraction with v1.6.0 (local) and xpub-extraction via a local Appimage (1.6.0) remote to a specter on a raspiblitz (1.5.0). Works both like a charm. Closing this issue.

**Closed by k9ert** 2021-09-02 10:07 UTC
Labels: bug, hw_jade
