### ISSUE TITLE
Save as pending transaction fatal error

### ISSUE THREAD

**Issue by daprovik** [cryptoadvance/specter-desktop#1063] opened 2021-03-28 22:44 UTC
Working on Testnet, multisig 2 of 3, desktop Windows application, v1.2.2.

Acquired 2 signatures, receiving fatal error after clicking Save as pending. Am able to go back to and see the signed transaction saved though, able to send.

_____________________

Server error!
Exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Back to the main page

Details:
Traceback (most recent call last):
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1926, in dispatch_request
  File "flask\app.py", line 1908, in raise_routing_exception
  File "flask\ctx.py", line 350, in match_request
  File "werkzeug\routing.py", line 1945, in match
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Please let us know! Create an issue or ping us on Telegram to fix it.

**Comment by ben-kaufman** [comment] 2021-04-01 09:54
Can you please update to 1.3.0 and see if that still happens, might have been some glitch if it's not repeating itself...

**Comment by ben-kaufman** [comment] 2021-04-04 14:23
Closing for now as I couldn't reproduce, probably some glitch. Please reopen if this still happens with version `1.3.0`

**Closed by ben-kaufman** 2021-04-04 14:23 UTC

**Comment by daprovik** [comment] 2021-04-10 01:09
Hi Ben, I'm upgrading to ver 1.3.0 but unable to get the SHA256 hash
through Command Prompt, getting error:

C:\Users\[xxxxxxxx]Downloads>certUtil -hashfile Specter-Setup-v1.3.0.exe
SHA526
CertUtil: -hashfile command FAILED: 0xd0000225 (NT: 0xc0000225
STATUS_NOT_FOUND)
CertUtil: The object was not found.

Getting hash for ver 1.2.2 works...

C:\Users\[xxxxxxxx]\Downloads>certUtil -hashfile Specter-Setup-v1.2.2.exe
SHA256
SHA256 hash of Specter-Setup-v1.2.2.exe:
3faf73fb438ed3065a66c4569f34e09ee8c34a11eb5c2f3cb3e824a0b630145e
CertUtil: -hashfile command completed successfully.

I'm running Windows 10 Home.

It did work in Powershell with this command though:

PS C:\Users\[xxxxxxxx]\downloads> certUtil -hashfile
.\Specter-Setup-v1.3.0.exe SHA256
SHA256 hash of .\Specter-Setup-v1.3.0.exe:
610a7ede613abbb6eb25a4bdb71d4af865919eddb6f817df3053668986b98d27
CertUtil: -hashfile command completed successfully.

Btw ver 1.2.2 doesn't load at all now, it shows a blank screen with error:
Internal Server Error

The server encountered an internal error and was unable to complete your
request. Either the server is overloaded or there is an error in the
application.

**Comment by ben-kaufman** [comment] 2021-04-13 09:45
Looks like for v1.3.0 you have a typo writing SHA526 instead of SHA256. Is that the issue?

**Comment by daprovik** [comment] 2021-04-13 13:25
You are right, what a newb mistake, thanks.
