### ISSUE TITLE
unable to start specter Ubuntu 22.04

### ISSUE THREAD

**Issue by taken2jail** [cryptoadvance/specter-desktop#2407] opened 2024-01-08 05:17 UTC
**Describe the bug**
when trying to run specter with the command python3 -m cryptoadvance.specter server, it gives an import error of "File "/home/ar_15/.local/lib/python3.10/site-packages/flask/helpers.py", line 14, in <module>
    from werkzeug.urls import url_quote
 
**To Reproduce**
1. Go to command line and type or copy and paste python3 -m cryptodance.specter server
2. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Where is your node running: [e.g. raspiblitz, MyNode, umbrel, local(internal), local(external)]
 - Where is your specter running: [e.g. Raspiblitz, Node, umbrel, binary]
 - If you're running a binary, which OS: [e.g. Linux, MacOs, Windows]
 - Specter Version [e.g. 1.9.4]

**Additional context**

**Comment by k9ert** [comment] 2024-01-08 15:57
Do you use a pyenv? Have you installed all dependencies? Which procedure did you follow?

**Comment by taken2jail** [comment] 2024-01-08 19:45
> Do you use a pyenv? Have you installed all dependencies? Which procedure did you follow?

I do not use pyenv and dont know what it is. I followed the guide under Installing speceter with Pip on a macbook which is running ubuntu. I also tried in with my virtual machine on my nas and still run into the same issue.

**Comment by k9ert** [comment] 2024-01-15 10:01
My guess is that you're not matching the prerequisites. Does the installtion via pip worked without issues? Please attach logs/screenshots which prove that the installation is fine.
Consider to use a platform-specific app!

**Comment by k9ert** [comment] 2024-01-15 10:05
Ups, sorry, this seem to be a duplicate of https://github.com/cryptoadvance/specter-desktop/pull/2399

We hopefully soon have a fix! I'll close this for now.

**Closed by k9ert** 2024-01-15 10:05 UTC
Labels: question
