### ISSUE TITLE
can't log in to specter desktop 15

### ISSUE THREAD

**Issue by jkariv** [cryptoadvance/specter-desktop#1327] opened 2021-08-02 10:39 UTC

**Comment by k9ert** [comment] 2021-08-02 16:06
This might be a duplicate of #1320 which is fixed but not yet released. As a workaround, try to restrict your browser to only use english language.

Alternatively, you can fix it yourself (if you don't use the App) via replicating this fix:
https://github.com/cryptoadvance/specter-desktop/commit/e24a75dbd35342b3c16af72540beb4377bd055a2

**Comment by k9ert** [comment] 2021-08-31 11:34
Fixed with `v1.5.1`. Closing.

**Closed by k9ert** 2021-08-31 11:34 UTC
