### ISSUE TITLE
Specter v1.3.1 not starting

### ISSUE THREAD

**Issue by tehelsper** [cryptoadvance/specter-desktop#1151] opened 2021-05-08 16:59 UTC
Several myNode users have reported an issue with Specter starting after upgrading to v1.3.1. The error is related to loading the Specter config file and removing it allows Specter to load properly. I'm working on getting exact error messages and more info.

It appears to only affect users who have used Specter before and saved config items.

**Comment by ben-kaufman** [comment] 2021-05-10 06:06
I believe the issue is with the config file getting corrupted. Is it possible during the update process the file is getting damaged?

**Comment by tehelsper** [comment] 2021-05-11 03:53
I really don't think so - it's designed so the config files specifically are not modified during an upgrade or re-install. Those files within the installed Specter folder are symlinked to a file on the external drive so the config survives upgrades and even re-flashing the SD card.

The issue seems to have appeared after the 1.3.1 upgrade and has effected a number of users. Is there any chance the config file processing was accidentally changed in some non-backwards compatible way?

**Comment by ben-kaufman** [comment] 2021-05-11 09:18
No, but even in such a case the error would've been different. In such a case where Specter doesn't start up it can only be due to config files which got corrupted.

**Comment by tehelsper** [comment] 2021-05-11 23:58
OK, thanks. There's also a chance my script to auto setup the local BTC info is clobbering something. Perhaps the upgrade isn't the issue - just the first reboot after setting up Specter.

**Comment by k9ert** [comment] 2021-09-02 10:16
Is this issue still relevant? The link to mynodebtc/mynode#532 seem to be somehow unrelated?

**Comment by tehelsper** [comment] 2021-09-03 02:06
Yeah, the link to that issue is irrelevant. This issue still occurs, but I added a button in myNode to delete the Specter config file which is then regenerated after it restarts and Specter starts working again.

**Comment by k9ert** [comment] 2021-11-30 16:50
Would be great to get some logfiles. In the meantime, i'll close that issue. Please reopen any time you have new information if this still occurs (had one severe data-corruption-bug fixed in the meantime)

**Closed by k9ert** 2021-11-30 16:50 UTC
Labels: bug, research needed
