### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by AlbMacc** [cryptoadvance/specter-desktop#995] opened 2021-03-03 01:09 UTC
When the screen is not big enough, the window doesn't appear entirely and the only way to see and move to the lower part or to go back to the upper part is with Tab.
It would be useful to add a scroll bar on the right side.

**Comment by GBKS** [comment] 2021-07-26 13:52
With which operating system, browser and screen resolution and on what page do you see this problem? I can't reproduce it.

**Comment by relativisticelectron** [comment] 2022-02-26 06:42
Could this be a duplicate of https://github.com/cryptoadvance/specter-desktop/issues/673
If so it is resolved in https://github.com/cryptoadvance/specter-desktop/pull/1598

**Comment by moneymanolis** [comment] 2022-04-27 07:04
Addressed with #1580.

**Closed by moneymanolis** 2022-04-27 07:04 UTC
Labels: UIUX
