### ISSUE TITLE
Windows - Firefox - devices key table throws an error

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#666] opened 2020-11-21 18:28 UTC
the keys table in device wizard just doesn't appear

**Comment by k9ert** [comment] 2020-11-30 12:46
I'm not sure i understand the issue. The current master looks like this and console doesn't show errors?!

![image](https://user-images.githubusercontent.com/117085/100611889-54cbc380-3312-11eb-8115-0f9bd9cc4f41.png)

**Comment by ben-kaufman** [comment] 2020-12-06 07:26
Closing as duplicate of the more recent #729

**Closed by ben-kaufman** 2020-12-06 07:26 UTC
Labels: bug
