### ISSUE TITLE
Load device / wallet from Specter Desktop

### ISSUE THREAD

**Issue by davewhiiite** [cryptoadvance/specter-desktop#398] opened 2020-09-18 00:13 UTC
Importing from a saved Specter wallet or device doesn't seem to work in Specter Desktop on Ubuntu. Rebooted and tried several times. Workaround is to use the browser to upload the wallet file, which was successful. 

Software: Specter Desktop 0.7.2 (binary)
OS: Ubuntu 20.04
Bitcoin Core 0.20.1

**Comment by k9ert** [comment] 2020-09-30 10:32
We have several improvements for importing wallets, last was this one:
https://github.com/cryptoadvance/specter-desktop/pull/463

However this is not yet released. On  the other side it's not very clear what was the issue on your side and which way you imported the wallet (via "create wallet" or via "load wallets" from settings).

I'll close it for now and if it's still an issue for you after the release, feel free to reopen.

**Comment by stepansnigirev** [comment] 2020-09-30 12:16
It's not solved. The problem is in the GUI that doesn't show a warning like normal browsers when you are trying to upload the whole folder. We need to support uploads of zip files for that or find a way to show folder upload confirmation in the GUI.

**Comment by davewhiiite** [comment] 2020-09-30 15:39
Adding some detail: I actually tried to import because I was moving to a fresh install of Ubuntu 20.04. So I moved the whole .bitcoin directory to the new system, re-installed Specter Desktop, and then imported the wallet files using Specter in browser. What I found is that I actually could watch the wallet--see balances and UTXOs--but could no longer send from it (presumably broke whatever references Specter uses). The resultant error was something like "wallet not loaded in Bitcoin Core." --> manually loading the wallet file ($ bitcoin-cli loadwallet "specterxxxx/walletname") didn't seem to help. No outstanding issue for me, because I recovered the funds using Electrum and the seed phrase created by Specter (which works, btw!).

A possible solution: does Specter Desktop have the ability to recover a wallet by seed phrase? Electrum does this nicely, and would avoid much of these interoperability issues, when migrating, upgrading software, or switching computers.

**Comment by kravens** [comment] 2020-10-08 20:13
I also tried to load the folder with the backup files, but failed on OS: Windows10 with the Specter Desktop app v0.8.1.
Selecting the individual device files using "Choose files" in "Setting up a new device" tab also fails to load in the corresponding device name/type/xpubs.
Would be nice to get the "Load backup.zip" button included in a Recovery option.

**Comment by k9ert** [comment] 2020-10-12 11:56
I'm not sure why the zip-file is such a big deal. If you unzip it before uploading and then choose the folder (in the setting-tab), this is working seamlessly for me (on a raspiblitz).

> So I moved the whole .bitcoin directory to the new system, re-installed Specter Desktop, and
> then imported the wallet files using Specter in browser.

Depending on how you did import the wallet files (via folder upload in the settings?!) this should work assuming that you properly migrated the bitcoin-folder.
One thing to take care of is the specter-uid which you can find top-level in the config.json:
``` 
➜  .specter cat config.json | jq .uid
"8f48fad1ab847be5"
➜  .specter
```
This UID is used when creating wallets in bitcoin-core. Check the folders in .bitcoin-folder.

> I also tried to load the folder with the backup files, but failed on OS: Windows10 with the 
> Specter Desktop app v0.8.1.

Can you elaborate how this is failing? It usually gives you a traceback in the UI.

> Selecting the individual device files using "Choose files" in "Setting up a new device" tab 
> also fails to load in the corresponding device name/type/xpubs.

Can you open a new issue for that to not mix up things?

**Comment by kravens** [comment] 2020-10-12 13:27
@k9ert 
About loading the folder or files, on the Windows 10 desktop app it does not accept selecting a whole folder.
The loading of individual wallet files gave following traceback:
![image](https://user-images.githubusercontent.com/9646902/95751496-fe8dbd00-0c9e-11eb-9d27-56335583c543.png)
This instance of Specter was connected to a different BitcoinCore (0.20.1) node, so perhaps it's the specter-uid that causes this failure.
Anyhow it was possible to recover the same wallet by manually creating the wallet with same xpub and derivation path again.

**Comment by k9ert** [comment] 2020-10-13 19:15
Ah, ok, got it. Well that's nasty indeed. So this doesn't work with any browser on win10? It's worth testing with chrome and firefox.

**Closed** 2020-10-26 11:10 UTC
Labels: bug
