### ISSUE TITLE
Upload signed Multsig .psbt，specter prompts “failed to fetch”

### ISSUE THREAD

**Issue by caixiao-QA** [cryptoadvance/specter-desktop#1265] opened 2021-07-06 05:36 UTC
specter version：V1.4.6

Upload signed Multsig .psbt，specter prompts “failed to fetch”
![image](https://user-images.githubusercontent.com/37337093/124547405-a87d2d00-de5e-11eb-9887-16b657197502.png)

about transaction：
![image](https://user-images.githubusercontent.com/37337093/124547496-cfd3fa00-de5e-11eb-9e2e-b3d7c89423e6.png)

and,The psbt file before signing, and the file after signing, have been uploaded as attachments
[ColdCard-Multisig.zip](https://github.com/cryptoadvance/specter-desktop/files/6767542/ColdCard-Multisig.zip)

**Comment by k9ert** [comment] 2021-07-06 11:50
It's difficult to reproduce this issue only with the attached files. I tried to find that error-message in the code but couldn't. Can you please [check the logs](https://github.com/cryptoadvance/specter-desktop/blob/master/docs/faq.md#where-do-i-find-the-logs) ?

**Comment by caixiao-QA** [comment] 2021-07-13 11:59
[specter.log](https://github.com/cryptoadvance/specter-desktop/files/6808627/specter.log)

**Comment by k9ert** [comment] 2021-07-15 08:42
Thanks so far. I have some observations:
* I can see that your connection with Core doesn't seem to be that stable
* The logs doesn't look that buggy in July 06. Nothing in there which i could potentially relate to the error-message
* In 8th of July, i get twice something like this:
```
[2021-07-08 14:27:09,004] WARNING in fee_estimation: Failed to fetch fee estimation from mempool.space Tor hidden service. Using Bitcoin Core instead. Error: Expecting value: line 1 column 1 (char 0)
```
Looking at the code, i don't think this could potentially roll up to the UI like this and it would still be no explanation how this could potentially cut off to "Failed to Fetch". 
https://github.com/cryptoadvance/specter-desktop/blob/v1.4.6/src/cryptoadvance/specter/util/fee_estimation.py#L35

Another theory would be that this is completely a result of javacript-code in the browser. @ben-kaufman any thoughts on your side? How can we investigate this better. I guess i'd love to mark somehow error-messages with are coming from javascript to distinguish them from the ones coming via "flash".

**Comment by caixiao-QA** [comment] 2021-07-19 01:46
yes， The clock on the machine is right

**Comment by k9ert** [comment] 2021-07-21 12:56
Maybe you can try with v1.5.0 and maybe try to reproduce and then only attach the snippet in the logs where this happens? It's still a bit fuzzy for me where in the logs this is happening.

**Comment by k9ert** [comment] 2021-08-31 12:04
Is this still an issue on `v1.6.0` ?

**Comment by caixiao-QA** [comment] 2021-09-14 01:49
> Is this still an issue on `v1.6.0` ?

1.6.0 version does not appear

**Comment by k9ert** [comment] 2021-09-28 09:50
Cool, so this seems to be fixed. Closing this issue.

**Closed by k9ert** 2021-09-28 09:50 UTC
Labels: bug
