### ISSUE TITLE
Export PDF Back-up Issue

### ISSUE THREAD

**Issue by bwg1121** [cryptoadvance/specter-desktop#828] opened 2020-12-31 21:50 UTC
Hi - I am running v0.10.1.  

As a test I wanted to create a duplicate watch-only wallet in Electrum based on my Specter Desktop wallet.  I used the Master Public Key info provided in backup PDF, and entered this into Electrum.  It did not work.  No balance was shown in Electrum.

I then went back to my original json file export and tried a few different Master Public Keys.  I eventually found the correct mpk that showed my balance and transaction in Electrum.  However the correct mpk was not the one shown in the back-up pdf file.  Was this user error? Or should the correct mpk be showing in the back-up PDF?  

Thanks for the help!

**Comment by ben-kaufman** [comment] 2021-01-01 14:14
Hi, sounds strange, I checked and Specter PDF backups seems to work fine. Is there a chance the issue is with the derivation path used?

**Comment by bwg1121** [comment] 2021-01-01 22:44
So I am having a similar issue on two wallets - 1) a single key 2) a Multisig.  For both wallets the back-up PDF contains a Master Public Key (mpk) starting with xpub , but the mpk that worked in Electrum started with a zpub.

1) For the single key wallet I found the xpub mpk referenced in the back-up PDF within my json export file. So it looks like it is an address that was generated from my wallet / private key - just not the one being used?

2) For the multi-sig, however, I can't find the xpub mpk referenced in back-up pdf in my json exports or in Specter app (Devices --> Keys).  But I was able to recreate wallet using a mpk starting with Zpub.  This zpub address is in my json export, and in the Specter app.

Hope that makes sense., and this is the appropriate place to ask this question.  Appreciate the help.  Happy new year!

**Comment by maxidev** [comment] 2021-01-06 18:19
@ben-kaufman I think this has to do with what I reported on Telegram group. When you export PDF you only get XPUB bip32 master key, even when you use bech32.

**Comment by maxidev** [comment] 2021-01-06 18:24
I think that ideally, the PDF backup should show xpub, ypub and zpub when exported here:
![image](https://user-images.githubusercontent.com/5783552/103806067-3d7ba680-5033-11eb-99f5-9e38bb5701b4.png)

**Comment by k9ert** [comment] 2021-01-19 14:13
@moneymanolis  what do you think about this?

**Comment by ben-kaufman** [comment] 2021-01-20 10:28
This is already solved actually, master already allows to toggle between using the xpb and slip132 method, so closing this for now.

**Closed by ben-kaufman** 2021-01-20 10:28 UTC
Labels: UIUX, bug
