### ISSUE TITLE
Adding BitBox02 stops right before the pairing step

### ISSUE THREAD

**Issue by qertoip** [cryptoadvance/specter-desktop#944] opened 2021-02-11 21:39 UTC
BitBox02 works correctly with Electrum on the same machine meaning USB cable, udev rules, plugdev etc are all fine.

With Specter though, when adding new device of BitBox02 type, it starts promising by requesting to unlock device (BitBox02 password) but right after, when it should have shown the pairing step, it waits forever. This happens every time, retrying does not help. While with Electrum, it works well every single time.

I work with a single wallet app at the time, meaning when I test Specter, it is the only wallet running (Electrum verified killed).

Concerns Specter v0.10.4 on Linux. Works fine with Coldcard though. The issue is BitBox02 + Specter specific.

**Comment by hzoman** [comment] 2021-02-17 03:05
I previously opened this as an issue, and for some reason it was ignored and demoted to a "discussion" where no one sees it. Apparently actual bugs aren't taken seriously here. https://github.com/cryptoadvance/specter-desktop/discussions/779

The real kicker though is that despite all the marketing claims, according to this https://github.com/cryptoadvance/specter-desktop/issues/815 BitBox02 apparently doesn't even work with multisig in Specter (assuming you were somehow able to actually get it to pair, which I never did, and BB02's "support" was terrible).

**Comment by ben-kaufman** [comment] 2021-02-17 07:15
Hi, @qertoip which BitBox02 firmware are you using?
I've just tested with 9.4.0 and Specter 1.1.0 and could not reproduce the issue. 

@hzoman sorry, I haven't seen the issue you opened before, we're a very small team and sometimes things get lost under other issues... Feel free to ping me also on Telegram or Twitter if we miss an issue on the GitHub.
Regarding multisig support, it's already merged on HWI, and should be part of their next release. As soon and they make the release, we'll work on integrating it to Specter...

**Comment by benma** [comment] 2021-02-17 10:05
Have you tried pairing in the BitBoxApp first, and then using Specter? 

@ben-kaufman does Specter surface the HWI errors? HWI tells the user to pair in the BitBoxApp if unpaired.

**Comment by ben-kaufman** [comment] 2021-02-17 17:44
@benma thanks for chiming in :) I believe it should surface errors from HWI.

How can I "unpair" the bitbox02 to see how it reacts?

**Comment by benma** [comment] 2021-02-17 17:46
One way is to reset and restore the device.

Another way is to delete the pairing file on the computer. On Linux: `~/config/bitbox/bitbox02/bitbox02.json`. On macOS:  `~/Library/Application Support/bitbox/bitbox02/bitbox02.json`.

**Comment by ben-kaufman** [comment] 2021-02-17 18:01
Ok I see now, so it doesn't seem to return an error, but is just stuck with waiting for user CLI confirmation of the pairing. Is there a way to do this pairing with HWI without CLI?

**Comment by benma** [comment] 2021-02-17 18:12
Did you launch the app on the CLI? What if you launch it without an attached CLI?

The HWI code is supposed to give an error if there is no CLI:

https://github.com/bitcoin-core/HWI/blob/4caa682e63fdec45a6a63828848f29f150026a1b/hwilib/devices/bitbox02.py#L98

```
Device not paired yet. Please pair using the BitBoxApp, then close the BitBoxApp and try again.
```

If you use the HWI Python libs directly, you can also set your own NoiseConfig instance to handle the pairing, to handle the pairing in the GUI directly, similar to in hwi-qt. That would be best if possible.

https://github.com/bitcoin-core/HWI/blob/4caa682e63fdec45a6a63828848f29f150026a1b/hwilib/gui.py#L361

**Closed** 2021-02-20 14:08 UTC
Labels: bug, hw_bitbox
