### ISSUE TITLE
1.7.0 osx hashes don't match

### ISSUE THREAD

**Issue by nolim1t** [cryptoadvance/specter-desktop#1458] opened 2021-11-02 12:09 UTC
1. Downloaded 1.7.0 OS X binary from https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.7.0
2. Downloaded the SHA256SUMS
3. downloaded specterd-v1.7.0-osx.zip 
4. run `sha256sum specterd-v1.7.0-osx.zip `

**Expected Result**

Hash should be

```
44a10e9127fa667467b30b6fbc7fb495cb836520ef87b07a3fed03a6aceae30b
```

**Actual result**

```bash
% sha256sum specterd-v1.7.0-osx.zip 
920ca8ecebfa055c69c36de6d84126d1a755d2f40e0ac49c0fbd5b5f08383850  specterd-v1.7.0-osx.zip
```

**Comment by calkob** [comment] 2021-11-02 12:28
I can confirm i get the same result as you.

SHA256 hash of specterd-v1.7.0-osx.zip:
920ca8ecebfa055c69c36de6d84126d1a755d2f40e0ac49c0fbd5b5f08383850
CertUtil: -hashfile command completed successfully.

Strange for this to be the case 14 days after release.  I also checked the windows.exe and it is correct.

**Comment by k9ert** [comment] 2021-11-02 17:27
Yes, indeed :-(. The reason was a screwed up MacOS build which i needed to repeat and then forgot to update hashes/signature.

That's now fixed and i hope it won't happen again due to massive improvements in the releases-process. Thank you both for bringing that up.

**Closed by k9ert** 2021-11-02 17:27 UTC
