### ISSUE TITLE
server error: no attribute 'network_info'

### ISSUE THREAD

**Issue by ChuckNorrison** [cryptoadvance/specter-desktop#446] opened 2020-09-27 20:07 UTC
This specter instance got updated from 0.5.5 to 0.8.0 via RaspiBlitz. This results in a login error:

```
Traceback (most recent call last):
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/controller.py", line 1030, in new_device
    label = request.form['label']
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/templates/device/new_device.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/templates/base.jinja", line 16, in top-level template code
    

  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/templates/base.jinja", line 17, in block "sidebar"
    {% block sidebar %}
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/templates/includes/sidebar/sidebar.jinja", line 20, in top-level template code
    {% if specter.network_info.version < 190000 %}
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'cryptoadvance.specter.specter.Specter object' has no attribute 'network_info'

```

**Comment by rootzoll** [comment] 2020-09-28 10:34
@ChuckNorrison thanks for early testing

@k9ert is this an update issue or what is the cause here? ... when I install specter 0.8.0 fresh on my RaspiBlitz login is working.

**Comment by stepansnigirev** [comment] 2020-09-29 23:13
@ChuckNorrison did you restart Specter after updating it?

Looks like the service is still running v0.5.0 but the templates are loaded from v0.8.0...

**Comment by ChuckNorrison** [comment] 2020-09-30 06:19
It worked after reinstall rather than update via Blitz menu. The blitz got restored with fresh sdcard and ends up with old kernel... maybe something with specter needs some investigations in this case. 

Workaround was easy, uninstall and reinstall with blitz menu. if nobody else can observe this behaviour, it seems not to be an issue

**Comment by k9ert** [comment] 2020-09-30 10:07
Depending on which raspiblitz-version you're using, it's possible to do an update. In later versions, it's no longer possible.
No idea what happened in this case. Seems like a pip-upgrade somehow didn't work but that's imho also unusual.

I'll close it for now, please reopen if this happens again.

**Closed by k9ert** 2020-09-30 10:07 UTC
