### ISSUE TITLE
UX - Devices - xpubs missing?

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#1646] opened 2022-03-31 22:29 UTC
I can't see the xpubs of the devices in v1.9.0
![image](https://user-images.githubusercontent.com/47259243/161160761-2733da6b-74c1-4142-a044-fb6f412d0ee1.png)

**Comment by k9ert** [comment] 2022-04-01 16:12
I just tried and couldn't reproduce on Mac Binary with trezor one device.
Does it make a difference if you check via the browser? Is there anything in the logs?
Can you check the console logs:
* View/Toggle Developer Tools
* Switch to console
* Check for the output
![image](https://user-images.githubusercontent.com/117085/161301971-264221d2-e4dc-4a88-aad6-44153e7f4dae.png)

**Comment by stepansnigirev** [comment] 2022-04-08 11:18
That's happening because the table with xpubs doesn't have a minimal height - it reduces to zero when the window size is small.
![Peek 2022-04-08 13-18](https://user-images.githubusercontent.com/1706012/162425632-3ae0ddaf-ca58-4be9-9769-085af3b84ae7.gif)

**Comment by k9ert** [comment] 2022-04-20 09:03
I think that's solved in master with @moneymanolis overhaul PR, right?! I guess we need a new release.

**Comment by moneymanolis** [comment] 2022-04-20 09:12
Yes, it is, also just double checked. I removed having a general scrollbar from the table-holder class. Closing this issue, since #1580 has already been merged.

**Closed by moneymanolis** 2022-04-20 09:12 UTC
