### ISSUE TITLE
Attempting to sign tx when input utxo is not yet confirmed fails permanently

### ISSUE THREAD

**Issue by MattDHill** [cryptoadvance/specter-desktop#814] opened 2020-12-28 03:54 UTC
I created an unsigned tx with an input pointing to a txid that had not yet been mined. Specter recognized the unconfirmed balance and permitted me to create the unsigned tx. When I attempted to sign the tx using a Trezor, specter failed with message `txid not found` or something similar. Even after the tx confirmed, the "Send" tab continued to display "Available Funds: 0 BTC", despite the original tx being confirmed and available and showing correctly in the "Transactions" tab. Somehow creating and failing to sign the original tx resulted in Specter believing the funds were no longer available. I have not dug into the DB or the code to determine the source of this error. Happy to do so if the solution is not readily apparent based on the description above.

**Comment by MattDHill** [comment] 2020-12-28 04:13
Fix was easy enough, just deleted the wallet and recreated/rescanned. BUt not sure what caused the initial discrepancy.

**Comment by ben-kaufman** [comment] 2020-12-30 06:31
Sounds strange, when exatly did the message appear? After signing, or after clicking send transaction? (or something else?) Also, I assume Specter version used is 0.10.4?

**Comment by ben-kaufman** [comment] 2021-02-26 08:48
I couldn't reproduce this sol far... anyway, in v1.2.2 you should be able to manually unfreeze such UTXO even if Specter accidentally locked it like this. Closing for now then but feel free to open if it's still happening.

**Closed by ben-kaufman** 2021-02-26 08:48 UTC
Labels: bug
