### ISSUE TITLE
Ledger: Internal error: (0x6a80',' Error in command',")

### ISSUE THREAD

**Issue by NTXAg10** [cryptoadvance/specter-desktop#1908] opened 2022-10-04 14:00 UTC
**Describe the bug**
I'm using v1.10.3 as it's the last version to support the Ledger Nano S/X. If you want to make a transaction, or verify an address on the device, and you have to confirm the transaction with the publisher, the error message comes (Internal error: (0x6a80',' Error in command',").) 

**To Reproduce**
1. Select wallet associated with ledger s/x
2. Click on Receive
3. Select Display Address on Device
4. Specter will detect device via USB. 
5. Error occurs 

This also happens when trying to send/sign a transaction.

**Expected behavior**
I’d like this resolved as I cannot use a ledger device on Specter until this is fixed. 

**Desktop (please complete the following information):**
 - Where is your node running: Local BTC Core
 - Where is your specter running: Raspberry PI, same device as node
 - Browser Chromium

**Additional context**

**Comment by fwittingham** [comment] 2022-10-05 16:55
Same problem with an install in Raspibolt V3 

Specter Desktop v1.13.0

**Comment by jiashanlu** [comment] 2022-10-07 12:22
Same problem with an Umbrel setup

**Comment by moneymanolis** [comment] 2022-10-07 13:56
Looks like a duplicate of the issue #1840 - should be fixed with the upgrade of HWI in this PR https://github.com/cryptoadvance/specter-desktop/pull/1909. The issue was with the hwi library. 

We have a pre-release with this upgrade of hwi. If someone can try it out with this release, that would be helpful: 
https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.13.1-pre1

**Closed** 2022-10-12 16:19 UTC
Labels: duplicate
