### ISSUE TITLE
Input field text is very hard to see on Firefox

### ISSUE THREAD

**Issue by vindard** [cryptoadvance/specter-desktop#1092] opened 2021-04-03 14:19 UTC
This issue only affects Firefox and works fine on Chrome/Chromium & Tor Browser

### The Issue & Potential Solution

The gif below (click for full resolution) shows how the text in form fields (`input` tag) appears in Firefox (on the left) vs. Chromium (on the right). In messing around with the CSS I found that the `font-weight` property is what is affecting this and it seems to have no effect in Chromium-based browsers.

This seems like it could be a pretty easy fix to help Firefox users without affecting other Browser users so I thought I'd submit here for consideration.

Thanks again for a really great product! :heart_eyes: 

![Peek 2021-04-03 10-14](https://user-images.githubusercontent.com/17693119/113481052-6ca08900-9465-11eb-8897-faa4156b39c1.gif)

**Comment by moneymanolis** [comment] 2021-05-13 14:59
I couldn't reproduce the issue. The value text is visible in white color as specified in the CSS class. If this issue pops up with other Firefox users one could think about specifying the CSS attribute. e.g.: `input[value]{color: #fff;}`. I would close for now.

**Comment by vindard** [comment] 2021-05-13 15:45
It looks like it may be an **_Ubuntu-only thing_**. I just tried it in Firefox inside a Windows VM on the same machine and there wasn't an issue.

**Comment by moneymanolis** [comment] 2021-05-13 16:09
OK, thanks for testing that. I think @k9ert could reproduce it under Linux as well, Kim can you check whether adding `input[value]{color: #fff;}` helps?

**Comment by go-brrr** [comment] 2022-04-04 20:47
It looks like this issue may have more to do with Firefox inheriting theming from the Linux OS rather than anything wrong with Specter's CSS. I confirmed that modifying the css with the `input[value]{color:#fff}` doesn't make a difference.

Searching around for a fix led me to several threads like this one:
https://askubuntu.com/questions/936716/disable-system-style-for-firefox-form-input-elements

**Comment by moneymanolis** [comment] 2022-04-07 12:41
Thanks for the link, @go-brrr.

**Comment by PaarthAgarwal** [comment] 2023-01-17 14:46
![Screenshot from 2023-01-17 20-13-51](https://user-images.githubusercontent.com/86092410/212928859-74dd837b-7e1a-460f-9f99-8da8c895245f.png)
It appears to be like this in firefox on ubuntu. Should I remove this line https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/static/styles.css#L407?

**Comment by moneymanolis** [comment] 2023-01-17 15:46
@PaarthAgarwal probably not worth it [given the UI revamp ](https://github.com/cryptoadvance/specter-desktop/pull/1991)that should fix that.

**Comment by PaarthAgarwal** [comment] 2023-01-17 15:56
> @PaarthAgarwal probably not worth it [given the UI revamp ](https://github.com/cryptoadvance/specter-desktop/pull/1991)that should fix that.

Ui revamp is looking cool 🤯

**Comment by k9ert** [comment] 2023-02-20 14:35
Fixed with the new UIUX.

**Closed by k9ert** 2023-02-20 14:35 UTC
Labels: bug, good first issue, UIUX
