### ISSUE TITLE
Standalone HWI-enabled PSBT signing mini app

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#37] opened 2019-11-24 04:46 UTC
In conjunction with #7 I'd like to build a standalone companion app that would leverage the existing codebase to allow for remote multisig partners to sign PSBTs with usb hardware wallets.

We can already support Coldcard downloaded PSBTs and Specter QR code PSBT signing with remote multisig partners by sharing the webserver's TOR onion url with them (though with no current security model it's probably not ideal to give all signers full access to the Specter Desktop UI). But usb wallet support requires a local install, rendering remote co-signers out of luck.

Projects like [flaskwebgui](https://github.com/ClimenteA/flaskwebgui) and [PyFladesk](https://github.com/smoqadam/PyFladesk) look like pretty promising ways to package a Flask site as a standalone app that can then be packaged and installed on any OS via PyInstaller.

It should be straightforward then to re-use the existing Specter HWI UI flow (detect-unlock-sign) in a separate standalone app that is just intended for remote PSBT signers. In its simplest form the PSBT can be transmitted to the signer through some secure means and then pasted/uploaded into the standalone signing app. The signed PSBT can then be downloaded and transmitted back. This could all be accomplished with any PSBT-compliant signing app, of course. But I haven't come across any that are strictly light clients (i.e. co-signers shouldn't need a full node, Electrum, etc just to sign a PSBT).

A slightly more advanced version could take advantage of our Tor layer and have the standalone app accept a Specter Desktop onion address so it can retrieve the unsigned PSBT from the server, have the user sign it, and then automatically send it back for the Specter Desktop to combine and transmit when complete.

**Comment by kdmukai** [comment] 2019-11-24 06:26
Some early progress, some early frustrations in my dev branch:
https://github.com/kdmukai/specter-desktop/tree/psbt_signing_app/src/signer

The good news is that `flaskwebgui` is successfully launching my mini app in its own standalone browser window.

Struggling with python imports across the two apps. Using two ugly workarounds for now:
* soft link added in the `signer` app to point to the `specter` app in order to do the import to add the HWI blueprint.
* `signer` templates are currently under specter/templates/signer. Had a more isolated version working but that also relied on more soft links.

**Comment by k9ert** [comment] 2019-11-25 13:58
Cool idea! However, i'd like to definitely avoid soft-link magic like that. I'd probably prefer to have the mini-app rather more close coupled to avoid symlinks but they definitely should have different blueprints. So speaking within the current setup, we would have a server.py and a server-miniapp.py and they use different blueprints.

Isn't it possible to share stuff between within the same app but different blueprints?

**Comment by kdmukai** [comment] 2019-11-25 14:34
Yeah, I hate the soft links, too. I was trying to maintain app-level separation, but still be able to import the `hwi` blueprints in. Every time I think I've worked out python's import pitfalls another one finds a way to bite me.

If I can't work out the imports, I'll take your approach and have them live parallel lives in the same structure.

**Comment by kdmukai** [comment] 2019-11-25 14:35
Quick update: I implemented #7 last night in preparation for delivering in-progress psbts to this standalone app. In retrospect I should have done that in its own branch so I could independently submit that change, but for now it'll be tied up here.

**Comment by stepansnigirev** [comment] 2019-11-26 08:19
Awesome idea! I didn't think about remote consigners yet, but it is definitely an important use-case! Can't wait to try your miniapp =)

**Comment by ben-kaufman** [comment] 2020-12-06 07:39
Closing for now as we have the HWI-Bridge mode for now (and since the issue is quite old 😄 ). Please reopen if you think it should be open still.

**Closed by ben-kaufman** 2020-12-06 07:39 UTC
Labels: enhancement
