### ISSUE TITLE
Unable to add wallets with desktop application [sqlite error]

### ISSUE THREAD

**Issue by kevinwin** [cryptoadvance/specter-desktop#983] opened 2021-02-25 04:16 UTC
When I try to add wallets through the desktop application I'm getting an error. 
When adding a wallet with a descriptor I get this error in particular

![image](https://user-images.githubusercontent.com/7491757/109102025-ee2e2a00-76f5-11eb-9423-99db98dd133d.png)

**Comment by ben-kaufman** [comment] 2021-02-25 05:27
Hi, are you on Bitcoin Core v0.21? How did you install Bitcoin Core?

**Comment by kevinwin** [comment] 2021-02-26 03:53
I'm connected to a remote node (umbrel). The core version is v0.21.

**Comment by ben-kaufman** [comment] 2021-02-26 08:09
Ok I see, so this seems to be a duplicate of #980 
We're working with Umbrel team to fix it, and will post updates on #980 when it's fixed. Will close this for now as a duplicate to keep the discussion in one place.

**Closed by ben-kaufman** 2021-02-26 08:09 UTC
