### ISSUE TITLE
Version mismatch between github release tag and the wallet version

### ISSUE THREAD

**Issue by nymkappa** [cryptoadvance/specter-desktop#2325] opened 2023-04-14 03:09 UTC
Hi,

I just upgraded to 2.0.1, downloading from https://github.com/cryptoadvance/specter-desktop/releases/tag/v2.0.1.

I ran the wallet, then a message "downloading binary from github" showed up for a very short time. Now in the about section of the wallet, it shows `v2.0.2.dev0+g6202c06a.d20230327`.

Is it some kind of automatic upgrade? If so, why is this version not showing in github release? How can I turn this off. I want to verify the signature of the binary I download.

Thanks.

**Comment by k9ert** [comment] 2023-04-16 12:48
This is very strange. Did you ever used a pip-installation or a dev-installation? What binary did you downloaded exactly? Which platform?

**Comment by nymkappa** [comment] 2023-04-16 13:16
> This is very strange. Did you ever used a pip-installation or a dev-installation? What binary did you downloaded exactly? Which platform?

I don't recall using pip and for sure never did a dev installation. But I had a previous installation of specter, which I "replaced" one prompted by macOS.

I used https://github.com/cryptoadvance/specter-desktop/releases/download/v2.0.1/Specter-v2.0.1.dmg

My OS is: macOS 13.3.1 (22E261)

Note: I just tried again and exact same result. I install the .dmg, login my wallet, and then I get a notification `Upgrade notification: new version 2.0.1 is available.` (which is funny since I just installed it).

Then the about page shows `Version: v2.0.2.dev0+g6202c06a.d20230327     UID: 18fc5ccc68b4fb12`.

**Comment by k9ert** [comment] 2023-04-19 13:11
I can't imagine how this could potentially happen. Can you check the running processes of where exactly the binary got executed? In linux, that would be something like:
```
ps uax | grep "cryptoadvance"
```

**Comment by nymkappa** [comment] 2023-04-25 06:58
```
nymkappa @ /Users/nymkappa $ ps uax | grep "cryptoadvance"
nymkappa         76035   0.0  0.0 408626896   1328 s011  S+    8:53AM   0:00.00 grep cryptoadvance
nymkappa @ /Users/nymkappa $ ps uax | grep "specter"
nymkappa         76038   0.0  0.0 408626896   1312 s011  S+    8:53AM   0:00.00 grep specter
nymkappa         75759   0.0  0.2 35279000 112988   ??  S     8:53AM   0:02.97 /Users/nymkappa/.specter/specterd-binaries/specterd server --no-filelog
nymkappa         75756   0.0  0.0 34065892   3716   ??  S     8:53AM   0:01.01 /Users/nymkappa/.specter/specterd-binaries/specterd server --no-filelog
```

Not sure how to see the path of the mac os application running, but here are all opened files by the application using mac os native activity monitor:

```
/
/Applications/Specter 2.app/Contents/MacOS/Specter
/private/var/db/oah/39d89dae22e403e19d9de44f94154e3d53f2d6185ba8d6065af1e731f31c86fb/acaac71f30715892ca1a33416cc1eed7a14250ccfdf6e237a4f0b2d968aa4500/Specter.aot
/usr/libexec/rosetta/runtime
/Library/Apple/usr/libexec/oah/libRosettaRuntime
/Applications/Specter 2.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
/private/var/db/oah/39d89dae22e403e19d9de44f94154e3d53f2d6185ba8d6065af1e731f31c86fb/d790b2c6a2184ffb97c5958d1967441ebfab2ba38a7cda30e646e32a0f3aacbf/Squirrel.aot
/Applications/Specter 2.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
/private/var/db/oah/39d89dae22e403e19d9de44f94154e3d53f2d6185ba8d6065af1e731f31c86fb/d22bc95e8b2a53f8af8b8115f873b50362ec97b2634c179213a0b10e925f89bf/Mantle.aot
/Applications/Specter 2.app/Contents/Frameworks/ReactiveObjC.framework/Versions/A/ReactiveObjC
/private/var/db/oah/39d89dae22e403e19d9de44f94154e3d53f2d6185ba8d6065af1e731f31c86fb/ffe13600af3d6b05b2820db7bdcde23a3346da122dc806a3d55dac542619491c/ReactiveObjC.aot
/Library/Preferences/Logging/.plist-cache.e2G99e3e
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/Common.loctable
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.x86_64.bin
/System/Library/CoreServices/SystemVersion.bundle/English.lproj/SystemVersion.strings
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
/private/var/db/timezone/tz/2023c.1.0/icutz/icutz44l.dat
/private/var/db/analyticsd/events.allowlist
/private/var/db/mds/messages/501/se_SecurityMessages
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/DictationManager.loctable
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
/private/var/db/oah/39d89dae22e403e19d9de44f94154e3d53f2d6185ba8d6065af1e731f31c86fb/c217b239af05c867c9bf6dae550dcf87ecd4ef2fe91fc697d5ed16c06bdb9eca/libffmpeg.dylib.aot
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantLight.car
/usr/share/icu/icudt70l.dat
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
/private/var/folders/lb/bc2h1trx28sbj9vp12zx42xw0000gn/0/com.apple.LaunchServices.dv/com.apple.LaunchServices-4035-v2.csstore
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/chrome_100_percent.pak
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/chrome_200_percent.pak
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/en.lproj/locale.pak
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/InputManager.loctable
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/MenuCommands.loctable
/System/Library/Caches/com.apple.IntlDataCache.le.kbdx
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/private/var/db/oah/39d89dae22e403e19d9de44f94154e3d53f2d6185ba8d6065af1e731f31c86fb/e57dda437aed95f8997e0063167a6381779c776abaff69463cb4a4e2afa68dcd/Electron Framework.aot
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Aqua.car
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLight.car
/System/Library/PrivateFrameworks/SFSymbols.framework/Versions/A/Resources/CoreGlyphs.bundle/Contents/Resources/Assets.car
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/resources.pak
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAqua.car
/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
/System/Library/Fonts/SFNS.ttf
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantDark.car
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
/usr/lib/libobjc-trampolines.dylib
/Users/nymkappa/Library/Application Support/Specter/GPUCache/data_0
/private/var/db/oah/39d89dae22e403e19d9de44f94154e3d53f2d6185ba8d6065af1e731f31c86fb/7cf8f1be82654d3d296e05c259a74e892802b78b181b65e363edc1ce006df61d/libobjc-trampolines.dylib.aot
/System/Library/Fonts/Helvetica.ttc
/Users/nymkappa/Library/Application Support/Specter/GPUCache/index
/Users/nymkappa/Library/Application Support/Specter/GPUCache/data_1
/Users/nymkappa/Library/Application Support/Specter/GPUCache/data_2
/Users/nymkappa/Library/Application Support/Specter/GPUCache/data_3
/Users/nymkappa/Library/Application Support/Specter/DawnCache/index
/Users/nymkappa/Library/Application Support/Specter/DawnCache/data_0
/Users/nymkappa/Library/Application Support/Specter/DawnCache/data_1
/Users/nymkappa/Library/Application Support/Specter/DawnCache/data_2
/Users/nymkappa/Library/Application Support/Specter/DawnCache/data_3
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/InfoPlist.loctable
/usr/lib/dyld
/dev/null
/dev/null
/dev/null
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.x86_64.bin
count=0, state=0x12
count=0, state=0x12
count=0, state=0xa
->0x1b1261e8198d3dc2
->0x3ca9f6da21169353
->0xaca5d1de7cd89962
->0xda8753c9e378317e
->0xe9388662f2fc0cfe
->0xaa62045b7f7a2510
/dev/urandom
count=0, state=0
->0x6c7bf050ed23c7ad
->0x8f5d4d339b156466
->0x1d40f3b687586c15
->0xecd67fec0d64d931
count=0, state=0xa
->0xafff8efc6cb7606e
->0x76c3c60f507b9bfa
->0x4bbbcd138bfb4026
->0x44c949ad5de49354
/Applications/Specter 2.app/Contents/Resources/app.asar
->0x2dd389383c930cc3
->0x4547d942081e9db1
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/chrome_100_percent.pak
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/chrome_200_percent.pak
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/en.lproj/locale.pak
/Applications/Specter 2.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/resources.pak
/Users/nymkappa/.specter/specterApp.log
/Users/nymkappa/Library/Application Support/Specter/Local Storage/leveldb/MANIFEST-000001
->0x79cb764053aec428
->0x996a7ee811cc6d49
count=0, state=0x8
/
/private/etc
/private/etc/hosts
/Users/nymkappa/Library/Application Support/Specter/Local Storage/leveldb/000003.log
/Users/nymkappa/Library/Application Support/Specter/Local Storage/leveldb/LOG
/Users/nymkappa/Library/Application Support/Specter/Local Storage/leveldb/LOCK
count=0, state=0x12
/Users/nymkappa/Library/Application Support/Specter/GPUCache/index
/Users/nymkappa/Library/Application Support/Specter/GPUCache/data_0
/Users/nymkappa/Library/Application Support/Specter/GPUCache/data_1
/Users/nymkappa/Library/Application Support/Specter/GPUCache/data_2
/Users/nymkappa/Library/Application Support/Specter/GPUCache/data_3
/Users/nymkappa/Library/Application Support/Specter/DawnCache/index
/Users/nymkappa/Library/Application Support/Specter/DawnCache/data_0
/Users/nymkappa/Library/Application Support/Specter/DawnCache/data_1
/Users/nymkappa/Library/Application Support/Specter/DawnCache/data_2
/Users/nymkappa/Library/Application Support/Specter/DawnCache/data_3
/Users/nymkappa/Library/Saved Application State/solutions.specter.desktop.savedState/data.data
/dev/null
->0x267feae720b81fe9
/Users/nymkappa/Library/Saved Application State/solutions.specter.desktop.savedState/windows.plist
->0x267feae720b82309
/Users/nymkappa/Library/Saved Application State/solutions.specter.desktop.savedState/window_1.data
->0x267feae720b82d31
/Users/nymkappa/Library/Application Support/Specter/Session Storage/LOG
/Users/nymkappa/Library/Application Support/Specter/Session Storage/LOCK
/Users/nymkappa/Library/Application Support/Specter/Session Storage/MANIFEST-000001
/Users/nymkappa/Library/Application Support/Specter/Session Storage/000003.log
```

**Comment by k9ert** [comment] 2023-04-27 12:07
Sorry, i didn't tried to reproduce it because it sounded ridiculous. I still don't know what went wrong at the release process but i can confirm that. The version is wrong for the 2.0.1 release!
I'll take care for the next releease that this doesn't happen again and will close this issue after the next release!

**Comment by nymkappa** [comment] 2023-04-27 20:59
If I understand properly the `specterd` binary is downloaded from github when I launch the wallet?

Is there any way to ship that within the release so we can verify that we're actually running the correct software?

Thanks.

**Comment by k9ert** [comment] 2023-05-01 10:15
As we don't have binary proven builds, it is almost impossible to ensure that the version on your machine corresponds to 2.0.1 because it does not. There is a slight difference which is probably a technical artifact which has been modified.

Give me 1-2 more days and i'll create a new version.

**Closed** 2024-01-12 10:47 UTC
