### ISSUE TITLE
Unable to create transaction: "Selected Coins Doesnt Cover Full Amount"

### ISSUE THREAD

**Issue by sako0938** [cryptoadvance/specter-desktop#1241] opened 2021-06-18 16:28 UTC
I am trying to consolidate coins in my wallet, but something is keeping me from sending all of the utxos that I want to send.

What is strange is it does seem to work with certain UTXOs and not others.

I have "Subtract fees from amount" checkbox checked, because my goal is to end up with a single utxo.

Specter Version: 1.4.5
Running using pip install method:
python3 -m cryptoadvance.specter server

Please let me know if you need any more data or screenshots. 
Thanks!

![specter3](https://user-images.githubusercontent.com/3485377/122590943-762a9d80-d01f-11eb-8c45-56056af7e8dc.png)
 
![specter1](https://user-images.githubusercontent.com/3485377/122590406-bdfcf500-d01e-11eb-80b8-245cd32b4b7a.png)
![specter2](https://user-images.githubusercontent.com/3485377/122590488-dff67780-d01e-11eb-9a1f-47bf269a8a3b.png)

**Comment by wr30** [comment] 2021-06-21 10:58
I’m having same exact issue, but I have no upgrades yet. Still on version 1.3.1. Have had 0 issues until this today. Will try to upgrade to 1.4.5 and see if it persists.

**Comment by sako0938** [comment] 2021-07-06 04:54
Im trying to track down the source of this bug. I modified wallet.py to print out the remainder that it is concerned about and it look to be a float issue.
```
            if selected_coins != []:
                still_needed = sum(amounts)
                for coin in selected_coins:
                    coin_txid = coin.split(",")[0]
                    coin_vout = int(coin.split(",")[1])
                    coin_amount = self.gettransaction(coin_txid, decode=True)["vout"][
                        coin_vout
                    ]["value"]
                    extra_inputs.append({"txid": coin_txid, "vout": coin_vout})
                    still_needed -= coin_amount
                    if still_needed < 0:
                        break
                if still_needed > 0:
                    raise SpecterError(
                        f"Selected coins does not cover Full amount! Please select more coins! {still_needed}"
                    )
```
This is the error I get, which shows its missing less than a satoshi, pointing to a zero float issue.

ERROR: Selected coins does not cover Full amount! Please select more coins! 5.551115123125783e-17

**Comment by sako0938** [comment] 2021-07-06 04:59
I modified the code again to instead compare the remainder to >= 1 sat instead of zero, and I was able to generate my PSBT. Ill try now to sign with my hww.

Let me know if this is PR worthy! Would love to be a contributer.
```
                if still_needed >= 0.00000001:
                    raise SpecterError(
                        f"Selected coins does not cover Full amount! Please select more coins! {still_needed}"
                    )
```

**Comment by sako0938** [comment] 2021-07-06 05:16
Coldcard still gives me an invalid psbt error...

**Comment by k9ert** [comment] 2021-07-06 10:59
I guess you're right qualifying that as a quite nasty float-issue. Unfortunately it's difficult for us to fix such edge-cases. Here is a recommendation where we try to fix that by calculating in satoshis, maybe it helps?!
```
            if selected_coins != []:
                still_needed = sum([ int(round(amount * 100000000)) for amount in amounts])
                for coin in selected_coins:
                    coin_txid = coin.split(",")[0]
                    coin_vout = int(coin.split(",")[1])
                    coin_amount = self.gettransaction(coin_txid, decode=True)["vout"][
                        coin_vout
                    ]["value"]
                    extra_inputs.append({"txid": coin_txid, "vout": coin_vout})
                    still_needed -= int(round(coin_amount * 100000000))
                    if still_needed < 0:
                        break
                if still_needed > 0:
                    raise SpecterError(
                        "Selected coins does not cover Full amount! Please select more coins!"
                    )
```
I changed the original code in two lines, first taking each amount and transforming it in satoshis before suming up:
```
still_needed = sum([ int(round(amount * 100000000)) for amount in amounts])
```
Then later substracting the satoshi amount from the "still needed":
```
still_needed -= int(round(coin_amount * 100000000))
```

Maybe you can try that?

**Comment by sako0938** [comment] 2021-07-06 16:44
I tried this code using satoshis instead of BTC to eliminate the floats, and while it was able to create a PSBT, the PSBT has the same sha256sum hash as my psbt from last night where the coldcard said "invalid psbt", I am starting to look around further forward and back into the flow to see what else might be wrong.

**Comment by ben-kaufman** [comment] 2021-07-06 17:02
Are you sure the issue is not with the ColdCard? Maybe you're using an old firmware?

**Comment by sako0938** [comment] 2021-07-06 17:09
Its in the v4 series, I can try updating it to the latest

**Comment by sako0938** [comment] 2021-07-06 17:13
Its v4.1.1 so its the latest coldcard firmware

**Comment by ben-kaufman** [comment] 2021-07-06 17:19
Is it a multisig or single sig transaction?

**Comment by sako0938** [comment] 2021-07-06 17:20
multisig

**Comment by ben-kaufman** [comment] 2021-07-06 17:21
There is a problem with ColdCard after updating the firmware from v3.x to v4.x that you have to re-import the multisig file to be able to sign transactions. Can you please try to do that and retry to sign?

**Comment by sako0938** [comment] 2021-07-06 17:38
Nice, I had to re-import from specter, and I tried signing, but it failed. Then I deleted all the old multisig setups, so the only one left was the new one I imported, and then it was able to validate the psbt and sign!

So do you think specter should still use integers/satoshis to eliminate the floating point issue, that I originally faced?

**Comment by k9ert** [comment] 2021-07-09 09:23
I think using floats for btc is a potential source for issues. This could have been one but it probably isn't. I'd accept PRs which is change calculations all based on integer satoshis rather than btc-floats if it's included with testing (also edge-cases). 
Until then: Don't change code for now reason.
Closing this for now.

**Comment by sako0938** [comment] 2021-07-09 16:52
Well this was a bug that prevented me and @wr30 from building the transactions we wanted, and the modified client code was what solved our problems. Im glad this is here to help others. I do wish you would understand that while it was working for the majority of people, there is a bug somewhere, whether it is because I'm running using python directly `python3 -m cryptoadvance.specter server`. If I get around to it I will try and make a PR (with testing)

**Comment by sako0938** [comment] 2021-07-09 16:53
My coldcard related issues was in addition to the floating point issue.

**Comment by k9ert** [comment] 2021-09-09 08:25
@sako0938  agree, closing this was imho a bit to fast. This is a real issue, even though it might be one which only occurs on edge-cases. Reopening it.

**Comment by sako0938** [comment] 2021-09-09 14:24
Thanks, maybe Specter should internally make `#satsthestandard`

**Closed** 2021-10-08 15:56 UTC
Labels: bug
