### ISSUE TITLE
Error when importing my HWW into Specter Desktop for Umbrel

### ISSUE THREAD

**Issue by sellyourcuckbucks** [cryptoadvance/specter-desktop#1473] opened 2021-11-14 15:06 UTC
I got the below error when importing a HWW (trezor, Ledger and Coldcard) into the specter app on the umbrell. Anyone know a fix?

TypeError: must be real number, not SpecterError

**Comment by k9ert** [comment] 2021-11-23 12:09
I'm closing this as a duplicate of #1483 as we have a PR there already.

**Closed by k9ert** 2021-11-23 12:09 UTC
