### ISSUE TITLE
preserve form status when creating a new tx

### ISSUE THREAD

**Issue by djpnewton** [cryptoadvance/specter-desktop#889] opened 2021-01-19 20:41 UTC
When creating a new tx (https://github.com/cryptoadvance/specter-desktop/blob/2a4450501e899743028f6692e6dca8837cca6607/src/cryptoadvance/specter/server_endpoints/wallets.py#L520) and an error is returned (eg 'invalid address') then the form inputs are returned to their default cleared state. It would be nice if the form status is preserved (recipient, amount, coin selection, fee etc)

We could pass the form state into the final render_template function 

Also we could move the "openpsbt"/"deletepsbt" code to the "send/pending" endpoint and the "importpsbt" code to the "send/import" endpoint to reduce the size of this function (and I think be a bit more logically consistent)

If this seems reasonable I can try and code up a PR

**Comment by ben-kaufman** [comment] 2021-01-20 10:33
Hi, yes I think that makes sense, if you'd like to do that it'll be very helpful!

This issue is actually a duplicate of #346, but I'll leave this open instead of the older one since it's more up to date :)

**Closed** 2021-02-12 14:15 UTC
