### ISSUE TITLE
v2.0.0-pre6: QR code slider for export not working properly

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2140] opened 2023-02-02 03:04 UTC
- QR code slider for export not working properly
- In Settings > Export > Export Wallet

https://user-images.githubusercontent.com/47259243/216220981-2fa44065-4883-4ebf-be2d-caf96dee0a61.mov

**Comment by moneymanolis** [comment] 2023-02-02 07:53
Duplicate of https://github.com/cryptoadvance/specter-desktop/issues/2126

**Closed by moneymanolis** 2023-02-02 07:53 UTC
Labels: bug, v2
