### ISSUE TITLE
UX edge cases for transactions with non-existing utxos

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1572] opened 2022-02-11 08:58 UTC
I found cases, where the behavior of specter is not ideal:

- A tx (signed, unsigned, or partially signed) is saved in the send --> Unsigned transactions.  Then another transaction that has a same utxo as input is confirmed on the blockchain.    Currently specter users will (perhaps) not know, that the tx cannot be valid anymore and continuing to collect signatures.  Similarly it would be good to know if a conflicting transaction is waiting in the mempool.
- I can currently import a tx of which a input utxo doesn't exist (perhaps because it was used in a previously confirmed transaction).    I got (once, not reproducible) the error "Could not import PSBT: Invalid PSBT magic."  I any case it imported the tx.

 
I think the priority for these cases is low, however it could be helpful for the user to handle these cases.

**Comment by relativisticelectron** [comment] 2022-02-15 10:00
In my description I was trying to focus on utxos that do not exist (or are already used up by a tx in the mempool).  (The locked utxos you discuss in https://github.com/cryptoadvance/specter-desktop/issues/1582  )

OK, I thought it would be not too difficult, then knowing that the tx is invalid BEFORE broadcasting it would be nice. 

Can we scan at least the mempool and warn that there is a conflicting tx in there?

**Comment by moneymanolis** [comment] 2022-02-15 20:16
@relativisticelectron `testmempoolaccept` is already implemented (it's done before broadcasting):
https://github.com/cryptoadvance/specter-desktop/blob/b9ec6447862a2ffcdee7fab280a57c6c924d0cb1/src/cryptoadvance/specter/server_endpoints/wallets_api.py#L159

There you can also see a `delete_spent_pending_psbts` function, which is defined here:
https://github.com/cryptoadvance/specter-desktop/blob/ef3483cc3374fbc8fd49f408b085db10f6411641/src/cryptoadvance/specter/wallet.py#L922

When introducing this function, there was a similar discussion, especially on which tx to check: https://github.com/cryptoadvance/specter-desktop/pull/1366

This was implemented back then:
"This PR checks if any of pending psbts are using inputs from new or broadcasted transactions, and deletes these psbts."

So, this addresses the scenario where a pending PSBT was spent by cosigners, it gets deleted.

As for "Can we scan at least the mempool and warn that there is a conflicting tx in there?":
There is the RPC call `getrawmempool`, which is also very performance costly. 
Spending an unconfirmed UTXO can only happen via manual selection in Specter currently. Wouldn't it be enough to trigger a warning / info  to the user when selecting such a UTXO in the front end?

@k9ert what do you think?

**Comment by k9ert** [comment] 2022-02-24 13:36
Great research! Performance is important. Having a power-tool rather than something which imposes usage policies seems to be also a good idea.
The proposal from @moneymanolis is already implemented in some #1580 , no?!

**Comment by relativisticelectron** [comment] 2022-02-24 19:25
> Great research! Performance is important. Having a power-tool rather than something which imposes usage policies seems to be also a good idea. The proposal from @moneymanolis is already implemented in some #1580 , no?!

https://github.com/cryptoadvance/specter-desktop/pull/1580 does not touch any import logic.



> There you can also see a `delete_spent_pending_psbts` function, which is defined here:
> 
> https://github.com/cryptoadvance/specter-desktop/blob/ef3483cc3374fbc8fd49f408b085db10f6411641/src/cryptoadvance/specter/wallet.py#L922
> When introducing this function, there was a similar discussion, especially on which tx to check: #1366

https://github.com/cryptoadvance/specter-desktop/pull/1366  does not to prevent importing psbts that spend non-existing utxos (I don't see in https://github.com/cryptoadvance/specter-desktop/pull/1366 where it would be checked, and I just tested it again).

**Comment by moneymanolis** [comment] 2022-02-24 20:36
The check at PSBT import is on my list, see this isse: (https://github.com/cryptoadvance/specter-desktop/issues/1582) So, I will close this for now so we don't have two issues running. I think most of the first part of your issue  ...

> A tx (signed, unsigned, or partially signed) is saved in the send --> Unsigned transactions. Then another transaction that has a same utxo as input is confirmed on the blockchain. Currently specter users will (perhaps) not know, that the tx cannot be valid anymore and continuing to collect signatures. Similarly it would be good to know if a conflicting transaction is waiting in the mempool.

... is already implemented. 

If you run into a concrete problem, though, feel free to open a new issue regarding this topic.

**Closed by moneymanolis** 2022-02-24 20:36 UTC
Labels: UIUX
