### ISSUE TITLE
Failed to start specterd - Error 1 (Invalid Function) in pathlib.py

### ISSUE THREAD

**Issue by CherryDT** [cryptoadvance/specter-desktop#1509] opened 2021-12-12 13:50 UTC
I just downloaded Specter and it fails to start (Specter Desktop encounter an error: specterd exited with code 4294967295. Check the logs in the menu!)

Logs:

```none
2021-12-12T13:46:35.189Z [info] : Framework Ready! Starting tray Icon ...
2021-12-12T13:46:35.292Z [info] : Framework Ready! Initializing Main-Window, populating Menu ...
2021-12-12T13:46:36.159Z [info] : Starting specterd C:\Users\david\.specter\specterd-binaries/specterd.exe server,--no-filelog
2021-12-12T13:46:45.592Z [info] : stderr-SPECTERD: INFO in server: pyinstaller based instance running in R:\Temp\_MEI305202

2021-12-12T13:46:45.594Z [info] : stderr-SPECTERD: INFO in server: Configuration: cryptoadvance.specter.config.ProductionConfig

2021-12-12T13:46:45.596Z [info] : stderr-SPECTERD: INFO in specter_migrator: Initiated MigDataManager(C:\Users\david/.specter\migration_data.json events:1 execs:0 )

2021-12-12T13:46:45.599Z [info] : stderr-Traceback (most recent call last):
  File "specterd.py", line 4, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "cryptoadvance\specter\cli\cli_server.py", line 114, in server
  File "cryptoadvance\specter\server.py", line 109, in init_app
  File "cryptoadvance\specter\util\specter_migrator.py", line 125, in execute_migrations
  File "cryptoadvance\specter\util\specter_migrator.py", line 106, in plan_migration
  File "pathlib.py", line 1180, in resolve
  File "pathlib.py", line 205, in resolve
OSError: [WinError 1] Unzul�ssige Funktion: 'R:\\Temp\\_MEI305202'
[17528] Failed to execute script specterd

2021-12-12T13:46:45.600Z [info] : stdout-Initializing HWI...

2021-12-12T13:46:46.152Z [error] : specterd exited with code 4294967295
2021-12-12T13:46:46.153Z [info] : child process exited with code 4294967295
```

"Unzulässige Funktion" is "Invalid Function" in English.

Since the error refers to my temp directory `R:\Temp`, I thought I should mention that my Temp directory is a RAM disk (using ImDisk).

**Comment by k9ert** [comment] 2022-01-06 14:59
I could not reproduce this issue. However, i did not try to setup a ramdisk, though. Can you deactivate the Ramdisk and check whether that's the issue? I can't imagine that but i also can't imagine what the underlying root-cause might be.

**Comment by CherryDT** [comment] 2022-01-06 15:01
Seems it's indeed the issue, and there is no solution until now. Dangit!

https://bugs.python.org/issue31842

**Comment by k9ert** [comment] 2022-02-06 20:43
I've updated pyinstaller which i guess has now better support for such kind of stuff. Watch out for a release `v1.8.2`. Might still need some more days.

**Comment by k9ert** [comment] 2024-01-16 13:54
Closing it for now.

**Closed by k9ert** 2024-01-16 13:54 UTC
