### ISSUE TITLE
Laptop not recognizing QR code

### ISSUE THREAD

**Issue by sahilc0** [cryptoadvance/specter-desktop#854] opened 2021-01-09 17:45 UTC
**Goal**
I'm trying to export a wallet file from one Specter to another via QR code. Both Specters are on separate laptops. 

**Issues**
After selecting Import, the camera opens to scan the exported QR code with the wallet information. However the laptop isn't able to recognize the QR code and just does nothing.

**Troubleshooting steps**
I've tried:
-  adjusting size of QR
- brightness
- distance from camera
- sent QR from online laptop to phone, to bring closer to camera of offline specter
- turned offline laptop online just in case

**Version Info**
Specter A (exporting) is running on a MyNode, through macOS.
Specter B (importing) is running on Windows 10, specter v1

Any idea what would be wrong here?

**Comment by sahilc0** [comment] 2021-01-12 19:24
Any ideas here @ben-kaufman?

**Comment by ben-kaufman** [comment] 2021-01-13 08:41
QR not recognized is almost necessarily a camera issue... So not sure much can be done.

**Comment by s-tikhomirov** [comment] 2021-01-17 12:29
Facing the same problem here. @ben-kaufman , what do you mean by camera issue? Does Specter expect the OS / camera software to implement QR recognition and parsing? Any hints on how this may work on Ubuntu?

**Comment by ben-kaufman** [comment] 2021-01-18 07:10
No, I just mean the camera probably too low-quality to scan the QR code, or there is not enough light in the room, or the QR is too dense for it, so you might need to get a better camera, or play with lighting, or if the QR is quite dense, try to animate it (if it's from Specter just clicking it should do it.)

**Comment by s-tikhomirov** [comment] 2021-01-18 21:41
It's a PDF backup from Specter printed out, so no option to animate it I'm afraid :D 

It's a bit unclear to me though, should Ubuntu be able to just read QR codes out of the box? Or should I install additional software like [Zbar](http://zbar.sourceforge.net/)?

**Comment by ben-kaufman** [comment] 2021-01-19 07:07
No it should work out of the box, Specter is packaged with a library to read that. Maybe try with some simpler QR with less data just to see if the issue is really with the QR being too dense?

**Comment by sahilc0** [comment] 2021-01-20 01:22
Update: what I ended up doing was:
- on the "offline" machine, first while it was online (and no keys touched), downloaded and loaded the Specter backup file
- then went offline/airplane mode
- continued on to pass txns with QRs offline

I did end up using the new computer, but I don't think I was having an issue with the txn QRs in the first place. It was mostly the wallet export QR that seems to be too big.

**Comment by ben-kaufman** [comment] 2021-01-20 10:57
What quorum were you using? I think from around 5 it's getting quite hard to scan due to too much data, but not sure we can do much about it, maybe split it like animated QR so you can scan both back? (though that could make it less straightforward with other software maybe)

**Comment by sahilc0** [comment] 2021-01-20 20:40
Yep my quorum is >= 5. 
True. Not a huge issue after I realized I can just load from the backup file (and **then** go offline) but still would be cool to go offline immediately and transfer.

Maybe the solution is as you said, animated, but just like any other QR? By default show the single one, but click to animate. That way will work both ways.

**Comment by ChristopherA** [comment] 2021-01-20 21:55
We are puzzling through UR/QR based Account Maps (xpub-only descriptors + metadata) that will be more compact and optimized for QR. This will allow for larger descriptors to fit into single QR, and URs inherently offers optional animated QR.

First step is to define better compact keysets (eg [fingerprint/path/to/0]xpub…) which is almost there, as we need it for better 48’ support.

/cc  @WolfMcNally

**Comment by k9ert** [comment] 2023-02-20 14:51
There is no a way to increase the size of QRs and even splitting them in several smaller QRs. Should be fixed.

**Closed by k9ert** 2023-02-20 14:51 UTC
Labels: UIUX
