### ISSUE TITLE
After upgrading to 1.5.0: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand

### ISSUE THREAD

**Issue by cercatrova21** [cryptoadvance/specter-desktop#1311] opened 2021-07-17 23:01 UTC
I upgraded my specter server from 1.4.6 to 1.5.0. I have set a user login on the webpage, where I login with the admin user. The login page is loading well, but after typing in my credentials this error message is showing up:

400 Bad Request: The browser (or proxy) sent a request that this server could not understand

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/cryptoadvance/specter/server_endpoints/auth.py", line 78, in login
    password = request.form["password"]
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 377, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

I did the upgrade with the following command: pip3 install cryptoadvance.specter --upgrade
Restarted the machine multiple times.

My system:

Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-77-generic x86_64)
On this machine, nginx is installed and acts as a reverse proxy. Port 443 -> ngninx -> Port 25541

**Comment by k9ert** [comment] 2021-07-19 08:09
Sounds like a nginx-misconfiguration. Can you post your config here as well, please?

**Comment by cercatrova21** [comment] 2021-07-19 13:39
Here's my nginx config file: (I replaced the personal information with DOMAIN1, DOMAIN2 and DOMAIN3)

server {
    location / {
        proxy_pass http://127.0.0.1:25441;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/DOMAIN1/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/DOMAIN1/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
        server_name DOMAIN2;
        location / {
                proxy_pass http://127.0.0.1:25441;
        }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/DOMAIN2/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/DOMAIN2/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    server_name DOMAIN3;
    location / {
        proxy_pass http://127.0.0.1:25441;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/DOMAIN3/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/DOMAIN3/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}



server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name DOMAIN1;
    return 301 https://$host$request_uri; # managed by Certbot


}


server {

        server_name DOMAIN2;
    listen 80;
    return 301 https://$host$request_uri; # managed by Certbot


}

server {

        server_name DOMAIN3;
        listen 80;
        return 301 https://$host$request_uri;

}

**Comment by k9ert** [comment] 2021-07-21 12:54
I tried with the default nginx-config which we're recommending in the revers-proxy document and that works for me, although i haven't tested with ssl. Your one looks ok although it seems to be a bit more complex with two domains and ipv6. 
Can you reduce it and try to reproduce with a more sophisticated one?

@stepansnigirev Maybe you have a hint here. Does v1.5.0 work for your VPS?

**Comment by k9ert** [comment] 2021-07-25 11:33
Ok, i got the root-cause after being able to reproduce it myself. I have created an own issue for this: #1320 
I'm closing this here. It's really a wonder you're the only one suffering here.

**Closed by k9ert** 2021-07-25 11:33 UTC
Labels: question

**Comment by n-i-e-n-o** [comment] 2021-07-27 13:27
> I upgraded my specter server from 1.4.6 to 1.5.0. I have set a user login on the webpage, where I login with the admin user. The login page is loading well, but after typing in my credentials this error message is showing up:
> 
> 400 Bad Request: The browser (or proxy) sent a request that this server could not understand
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/python3.8/dist-packages/cryptoadvance/specter/server_endpoints/auth.py", line 78, in login
>     password = request.form["password"]
>   File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 377, in __getitem__
>     raise exceptions.BadRequestKeyError(key)
> werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
> ```
> 
> I did the upgrade with the following command: pip3 install cryptoadvance.specter --upgrade
> Restarted the machine multiple times.
> 
> My system:
> 
> Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-77-generic x86_64)
> On this machine, nginx is installed and acts as a reverse proxy. Port 443 -> ngninx -> Port 25541

Same here with a RaspiBlitz!

**Comment by k9ert** [comment] 2021-07-29 10:16
A workaround for this issue might be to not use other languages than english. I'm not sure how to set that exactly on each browser but that should be a valid workaround.
