### ISSUE TITLE
Layout is broken on iPhone SE

### ISSUE THREAD

**Issue by dimaatmelodromru** [cryptoadvance/specter-desktop#388] opened 2020-09-12 23:28 UTC
![FC3008B8-8E1D-4E01-BC45-EFEB1FE0F7F6](https://user-images.githubusercontent.com/4951450/93006737-b62c9380-f568-11ea-9bd4-162b3bb52a39.jpeg)

**Comment by ben-kaufman** [comment] 2020-09-13 05:13
Hi, this should be fixed in the next version with #326

**Comment by ben-kaufman** [comment] 2020-09-22 06:57
Closed by #326 
Please reopen if the issue is still appearing.

**Closed by ben-kaufman** 2020-09-22 06:57 UTC
