### ISSUE TITLE
Importing 24 word seed phrase throws "Language not detected" error

### ISSUE THREAD

**Issue by aphex3k** [cryptoadvance/specter-desktop#2064] opened 2023-01-17 17:18 UTC
**Describe the bug**
When importing a 24 word seed phrase as Bitcoin core hot wallet, instead of creating the "device" it will throw a language not detected error. 

**To Reproduce**
1. Go to 'Add New Device'
2. Click on 'Bitcoin Core'
3. Select 'Import'
4. Paste 24 word seed phrase
5. Click 'Continue'

**Expected behavior**
The device should be created.

**Screenshots**
![image](https://user-images.githubusercontent.com/433270/212966658-1f99f020-bb9b-45fa-8c68-110aa667248d.png)

**Desktop (please complete the following information):**
 - Where is your node running: umbrel
 - Where is your specter running: umbrel
 - If you're running a binary, which OS: Linux
 - Browser: Brave
 - Specter Version: v1.14.3

**Additional context**
I tried separating the words with whitespace and newline but either attempt failed. I'm using the English dictionary.

Actually, when using newline => `Language not detected`
when using whitespace => `ERROR: Invalid mnemonic entered.`

**Comment by aphex3k** [comment] 2023-01-17 17:28
Here is why I think it is not working: The seed phrase is used by a core wallet already known/loaded to bitcoin core but not by specter desktop but a different software. The error is a little but misleading.

**Comment by mark-EthDev** [comment] 2023-01-17 21:23
Talk to Ledgerwallet Support on the [Live support chat]( https://explore-ledger.online/) so that your issue can be looked into.

**Comment by aphex3k** [comment] 2023-01-17 21:35
> Talk to Ledgerwallet Support on the [Live support chat](WARNING SCAM!) so that your issue can be looked into.

The above comment is a SCAM link! Do not follow the link. Block/Report the user.

**Comment by k9ert** [comment] 2023-01-20 10:19
#1658 seems related. There can also be a stacktrace be found:
```
Traceback (most recent call last):
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "flask_login\utils.py", line 269, in decorated_view
  File "cryptoadvance\specter\server_endpoints\devices.py", line 207, in new_device_mnemonic
  File "cryptoadvance\specter\util\mnemonic.py", line 42, in validate_mnemonic
  File "mnemonic\mnemonic.py", line 115, in detect_language
mnemonic.mnemonic.ConfigurationError: Language not detected
```
That feature has been implemented in [fc6521f](https://github.com/cryptoadvance/specter-desktop/pull/1660/commits/fc6521fd98642f76f65a7d111cfc1d3222375559) and [c3ae3d9](https://github.com/cryptoadvance/specter-desktop/pull/1660/commits/c3ae3d9932882080b4ba654dbec9568cd9981fee) . I don't think all languages are supported and i guess the error-message and UX should be improved here.
@moneymanolis can you qualify that better?

**Comment by k9ert** [comment] 2023-01-20 10:31
Just saw that you used the english language. So i just tried to reproduce on the master branch with 
```
ghost ghost ghost ghost ghost ghost ghost ghost ghost ghost ghost machine
```
That worked without an issue. Can you test that?!

**Comment by moneymanolis** [comment] 2023-01-20 12:14
Here is the link to the error from the upstream library from Trezor:
https://github.com/trezor/python-mnemonic/blob/e3b883007019c5156762aee8cdc3a31f3fc82c80/src/mnemonic/mnemonic.py#L68

> The seed phrase is used by a core wallet already known/loaded to bitcoin core but not by specter desktop but a different software.

Do you have a stacktrace?

If it looks like the one @k9ert posted (below again) it's rather unlikely. I am tagging @prusnak perhaps he can help us here to see in which direction to investigate.

```
Traceback (most recent call last):
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "flask_login\utils.py", line 269, in decorated_view
  File "cryptoadvance\specter\server_endpoints\devices.py", line 207, in new_device_mnemonic
  File "cryptoadvance\specter\util\mnemonic.py", line 42, in validate_mnemonic
  File "mnemonic\mnemonic.py", line 115, in detect_language
mnemonic.mnemonic.ConfigurationError: Language not detected
```

**Comment by moneymanolis** [comment] 2023-01-20 12:16
@aphex3k just to make sure, all the words you use are from the BIP39 list and the checksum is correct?
You could check this by entering it on a signing device for example. If you are just testing around you can double-check here as well:
https://iancoleman.io/bip39/

**Comment by prusnak** [comment] 2023-01-20 12:34
`detect_language` only uses the first word, so it would be best idea to share just the first word to narrow down the investigation

**Comment by aphex3k** [comment] 2023-01-20 16:43
first word in the mnemonic I tried is `about` but it looks like my seed is invalid anyways? I'm checking...

**Comment by aphex3k** [comment] 2023-01-20 16:51
My bad, apparently the mnemonic I tried is not BIP39. This can be closed...

**Comment by moneymanolis** [comment] 2023-01-20 20:02
OK, no problem, closing this now.

**Closed by moneymanolis** 2023-01-20 20:02 UTC
Labels: question
