### ISSUE TITLE
Specter won't connect to Coldcard over USB

### ISSUE THREAD

**Issue by KISBITCOIN** [cryptoadvance/specter-desktop#500] opened 2020-10-11 14:17 UTC
I'm attempting to create a new device with Coldcard over USB on Mac OS.

Running Specter 0.8.1
I've verified my Coldcard is recognized by my OS via terminal. 
Specter can connect to a trezor on my computer.
I've tried restarting the Coldcard, and restarted the computer. Nothing I can do to get the Coldcard to be recognized by specter.

**Comment by mflaxman** [comment] 2020-10-12 07:41
This could be a duplicate of https://github.com/cryptoadvance/specter-desktop/issues/476

**Comment by ben-kaufman** [comment] 2020-10-12 07:51
Yes it appears HWI is partly broken currently. Not sure what happened but suddenly it doesn't recognize ColdCard with v1.1.2 , which we currently use, and address verification seems broke both for trezor and coldcard both on v1.1.2 and on latest.

@mflaxman it would be helpful if you could try to verify too that the issue is with HWI. I tested both v1.1.2 and v1.2.0. For me they gave the above issues, but if you can confirm this is the case for you too (or not) it'll be very helpful. I'll be looking into these problems meanwhile and see if I manage to fix that...

**Comment by k9ert** [comment] 2020-10-12 11:20
Maybe @peter-conalgo or @nvk can help here, too?

**Comment by ben-kaufman** [comment] 2020-10-12 15:06
I actually managed to fix the issue with Coldcard when using HWI v1.2.0 
It doesn't seem to work with regular descriptor format with xpubs, but what I did was get the descriptor with the derived pubkeys from Bitcoin Core by calling the getaddressinfo method, and that way it works.

Still I'm curious why HWI 1.1.2 seems to stopped working with Coldcard suddenly...

**Closed** 2020-10-12 16:21 UTC
Labels: bug, hw_coldcard
