### ISSUE TITLE
Exception thrown when clicking on "click to configure" without a node connection

### ISSUE THREAD

**Issue by alluringambiguous** [cryptoadvance/specter-desktop#2262] opened 2023-02-25 15:24 UTC
**Describe the bug**
I found another bug trying to trace issue #2260 .  The sidebar shows a "click to configure" button (even when node is not connected), and when you click it, a server error was thrown.

**To Reproduce**
Remove your node / delete spectrum (also the state of a new user). Click on "click to configure" on the sidebar.
![66ca1e7e-6dff-4cff-b754-73a81eb97408](https://user-images.githubusercontent.com/67975841/221365128-6d636f04-430f-403e-a0c5-1c9e8069a27d.jpg)

which redirected me to 
![adc0b497-d1a4-477a-aa08-eec449d1de99](https://user-images.githubusercontent.com/67975841/221363528-611ff7c5-8bbb-4cd1-a8e9-50ca703e1bab.jpg)

This looks like a similar UI issue (as #2260 ), as the user is sent to `node/<node_alias>/` route, with an empty string as `<node_alias>`.
Again we can hide this UI element in the sidebar when the node is not connected.

**Comment by moneymanolis** [comment] 2023-03-09 09:41
This should be fixed in Specter v2. I can't reproduce on master.

**Closed by moneymanolis** 2023-03-09 09:41 UTC
