### ISSUE TITLE
Error after upgrade: cannot list UTXOs

### ISSUE THREAD

**Issue by jaonoctus** [cryptoadvance/specter-desktop#2301] opened 2023-03-12 21:11 UTC
**Describe the bug**
It's showing `Uncaught exception: unhashable type: 'list'` on my wallet.

**To Reproduce**
1. Upgrade from `lncm/specter-desktop:v1.14.2` to `lncm/specter-desktop:v2.0.0`
2. Open an existing wallet
3. Click on 'UTXO'

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/7918067/224573706-99402380-6e17-48b4-809d-6759a4ebe070.png)

**Desktop (please complete the following information):**
 - Where is your node running: Linux Ubuntu 22.04.2 LTS
 - Where is your specter running: Umbrel
 - Browser: Chrome 111.0.5563.64 (Official Build) (64-bit)
 - Specter Version: 2.0.0

**Comment by moneymanolis** [comment] 2023-03-13 08:37
Thanks for reporting, could you provide a stacktrace from the logs?

**Comment by jaonoctus** [comment] 2023-03-14 02:42
@moneymanolis sure,

## endpoint

 `/wallets/wallet/segwit/utxo_list`

## response

```json
{"error":"Uncaught exception: unhashable type: 'list'"}
```

## logs

```
[2023-03-14 02:37:32,569] ERROR in controller: Uncaught exception: unhashable type: 'list'
[2023-03-14 02:37:32,569] ERROR in controller: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cryptoadvance/specter/server_endpoints/wallets/wallets_api.py", line 425, in utxo_list
    tx["label"] = wallet.getlabel(tx["address"])
  File "/usr/local/lib/python3.10/site-packages/cryptoadvance/specter/wallet.py", line 1617, in getlabel
    if address in self._addresses:
TypeError: unhashable type: 'list'

[2023-03-14 02:37:32,569] INFO in controller: POST, /wallets/wallet/segwit/utxo_list
```

**Comment by moneymanolis** [comment] 2023-03-15 14:11
I can't reproduce the issue. Can you provide more context on the wallet? Is it a Liquid wallet perhaps? 
Do you have any special transactions?

From the stack trace and the relevant code part it looks like, here in `wallets_api.py`
```
    for tx in txlist:
        if not tx.get("label", None):
            tx["label"] = wallet.getlabel(tx["address"])
```

`tx["address"]` is a list and not a string. But, I am not sure why or how it could be a list. 

The other relevant code that determines the properties of a `TxItem` (in `txlist.py`) is this and I can't see how this generates a list ...
```
    @property
    def address(self):
        """Does it make sense to show an address for a transaction? Maybe yes in certain
        situations. For those, you can use this one:
        """
        if self.get("address"):
            return self["address"]
        all_outs = [out.to_dict() for out in self.psbt.outputs]
        my_outs = [out for out in all_outs if out["is_mine"]]
        my_receiving = [out for out in my_outs if not out["change"]]
        external = [out for out in all_outs if out not in my_outs]
        # decide what addresses to show
        if self.category in ["generate", "receive", "selftransfer"]:
            # either receiving only (if not empty), or only mine (if not empty), or all
            outs = my_receiving or my_outs or all_outs
        elif self.category in ["send"]:
            # keep only external addresses if they are present
            outs = external or all_outs
        else:
            # not sure what's the best here
            outs = my_receiving or my_outs or external or all_outs
        addresses = [out.get("address", "Unknown") for out in outs]
        self["address"] = addresses[0]
        return self["address"]
```
However, in the `txlist.py` for Liquid I found this (that is why I asked whether it is a Liquid wallet):

  `tx["address"] = addresses`
  
  
```

    def _update_destinations(self, tx, outs):
        # remove dummy and fee
        outs = [out for out in outs if out.get("address") not in ["Fee", "DUMMY"]]
        # process the rest
        addresses = [out.get("address", "Unknown") for out in outs]
        amounts = [out.get("float_amount", 0) for out in outs]
        assets = [out.get("asset", "ff" * 32) for out in outs]
        if len(addresses) == 1:
            addresses = addresses[0]
            amounts = amounts[0]
            assets = assets[0]
        tx["address"] = addresses
        tx["amount"] = amounts
        tx["asset"] = assets
```

@k9ert tagging you since you worked more on this part of the code base.

**Comment by BitcoinMechanic** [comment] 2023-03-15 17:21
In my case it's a standard bitcoin wallet, maybe there's some taproot stuff in there - nothing more esoteric than that.

**Comment by moneymanolis** [comment] 2023-03-15 17:28
> In my case it's a standard bitcoin wallet, maybe there's some taproot stuff in there - nothing more esoteric than that.

Taproot would be interesting though. Can you double check? Support for this is not optimal in Specter yet and it would help to reproduce the issue. 
We'd need to better understand when this happens exactly.

**Comment by jaonoctus** [comment] 2023-03-16 00:49
@moneymanolis it's a segwit signet wallet,

```json
{"label": "segwit", "blockheight": 114347, "descriptor": "wpkh([c4ebe510/84h/1h/0h]tpubDDnfYdvNsp3MEGLbFTNPGPRY3YjPzBva6Zj4gmdFXdskR1dmRQBsQa6qao35LCuVRAZCEZgvWV4Yvt7H8YrYAQpR6REnFuYBgyKvFPjeaXQ/0/*)#203u9xl6", "devices": [{"type": "bitcoincore", "label": "bitcoin core"}]}
```

**Comment by moneymanolis** [comment] 2023-03-16 17:03
I am closing this, only caused on signet, which we don't support. @BitcoinMechanic feel free to open a new issue with a stacktrace like above. I couldn't reproduce the issue with a taproot wallet.

**Closed by moneymanolis** 2023-03-16 17:03 UTC

**Comment by BitcoinMechanic** [comment] 2023-03-16 17:07
I just had it randomly work on embassyOS while still not working on regular specter desktop. Pretty confused. Will try and get more info and reopen issue.

**Comment by jaonoctus** [comment] 2023-03-19 23:31
FYI I just deleted the wallet and re-created it using the same device. It's working on signet as well.

I must be some weired label on the old wallet or something like that
