### ISSUE TITLE
Transaction unconfirmed for days despite current mempool not busy

### ISSUE THREAD

**Issue by lasamocal** [cryptoadvance/specter-desktop#1322] opened 2021-07-26 11:21 UTC
Hello,
I already used specter desktop 1.42 to send transactions, without any issues.
I upgraded to 1.50. (by following the udev readme commands, and using the appimage 1.50).
I sent a transaction (with enough fee), for days now.
It is still unconfirmed, despite the mempool having many mined block half empty since then.
The balance of the wallet has taken into consideration the transaction (total minus the transaction).
I have checked on mempool.space, and the transaction does not exist.
Why is that?
Should I reinstall?
Should I cancel the transaction? Is there a way to cancel it without additional fees? Does the cancel process involve risks, considering the context?
Regards

**Comment by glpok** [comment] 2021-07-29 09:14
(I am lasamocal. I had to change my account because I used a temporary mail for lasamocal account, and github requested a second code verification after some time)

I wanted to add the following details:
-I have checked on mempool, and the transaction does not exist at all; but I have checked the original address with the coins, the coins are still on it on the mempool, but not shown on the specter desktop wallet.
- I signed the transaction 1.42 but I sent the transaction in version 1.50

The matter is urgent on my part; if you have any possibility to answer me soon, it would be greatly appreciated.
Regards

**Comment by kdmukai** [comment] 2021-07-30 03:55
It sounds like you should use the abandon transaction option in Specter. If your transaction isn't found anywhere in the mempool, then I would guess that it has been purged for some reason. Abandoning the transaction has no impact on the coins that you've already confirmed haven't moved. The problem (if I understand correctly) is that the wallet is basically out of sync--it still thinks that transaction is out there but no one else knows anything about it. Abandoning the transaction just tells the wallet, "Hey, this unconfirmed transaction is never going to happen so forget about it."

**Comment by k9ert** [comment] 2021-08-02 16:02
Did that solve the issue? Can we close this issue?

**Comment by etherx-dev** [comment] 2021-08-10 23:19
I think the easiest way to abandon the transaction (I didn’t test this theory out) will be to install the Specter wallet in an separate environment so you don’t have to remove the current data structure incase of any need for debugging. So install on a different user or system and load the wallet seed and make sure the new  doesn’t share any signatures with the old one as that might be dangerous

**Comment by k9ert** [comment] 2021-08-31 11:38
Well, the way this is supposed to work is shown here:
https://github.com/cryptoadvance/specter-desktop/pull/991
There is a screenshot from the transaction-detail-page. Do you see that button?
I assume that yes and so i close this issue for now. Don't hesitate to reopen if necessary.

**Closed by k9ert** 2021-08-31 11:38 UTC
